feat(tx-next/video): add aside shows and share btns
mirror-tv/Tabris pull request #107
Opened 2024-04-22 10:40 UTC by v61265

### 描述
- 新增 video category 頁面側欄 shows 和分享和扭，包含 facebook plugin。
- 在此 PR 前的 query show 有其他功能嗎？如果沒有的話可以考慮拿掉 `sortOrder` 這個其實不會用到的欄位。
- 更改既有 function `formateHeroImage` 的 type，並加上預設值防止報錯。

2024-04-22 14:17 UTC, erase2004 requested changes
> 在此 PR 前的 query show 有其他功能嗎？如果沒有的話可以考慮拿掉 sortOrder 這個其實不會用到的欄位。

看 2.0 的程式碼，沒有用這資訊來顯示，應該僅作為 debug 使用，可以刪除

一個目前還不算嚴重的問題提出：
`UiHeadingBordered` 使用到 `<h1>` 標籤，然後在一些元件上被重複使用，
例如：`UiShowsList`，導致整體頁面有不只一個 `<h1>` 的情況

2024-04-22 14:17 UTC, erase2004 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +      console.log(data?.data?.allShows)
多餘的 console.log?

2024-04-22 14:17 UTC, erase2004 commented on packages/mirror-tv-next/components/shared/facebook-plugin.tsx
> +  const fbRootRef = useRef<HTMLDivElement>(null)
這沒有用到的樣子?

2024-04-22 14:17 UTC, erase2004 commented on packages/mirror-tv-next/components/category/video/ui-show-card.tsx
> +  isArtShow: boolean | null
目前 `UiShowList` -> `UiShowCard` 這條路徑上，沒看到 isArtShow 為 `null` 的情況，請問 `null` 的使用情境是？

2024-04-22 14:17 UTC, erase2004 commented on packages/mirror-tv-next/components/category/video/ui-links-list.tsx
> +export type LinkInfo = {
比較建議這個 type 放在 `UiLinkCard` 而不是 `UiLinksList` 當中

2024-04-23 07:21 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/ui-links-list.tsx
> +export type LinkInfo = {
了解，已於 [7c36179](https://github.com/mirror-tv/Tabris/pull/107/commits/7c3617984f0f21325ba48e19164b64dab8d9a5e5) 修改

2024-04-23 07:22 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/ui-show-card.tsx
> +  isArtShow: boolean | null
原始 query 到資料後有可能是 null 值，但確實 props 進去後有預設值就不會再 null 了，因此於 [7c36179](https://github.com/mirror-tv/Tabris/pull/107/commits/7c3617984f0f21325ba48e19164b64dab8d9a5e5) 將 null 移至 query 中的原始資料使用。

2024-04-23 07:22 UTC, v61265 commented on packages/mirror-tv-next/components/shared/facebook-plugin.tsx
> +  const fbRootRef = useRef<HTMLDivElement>(null)
對我改一改就忘記了 XD 已於 [7c36179](https://github.com/mirror-tv/Tabris/pull/107/commits/7c3617984f0f21325ba48e19164b64dab8d9a5e5) 移除。

2024-04-23 07:23 UTC, v61265 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +      console.log(data?.data?.allShows)
感謝提醒，已於 [7c36179](https://github.com/mirror-tv/Tabris/pull/107/commits/7c3617984f0f21325ba48e19164b64dab8d9a5e5) 修改

2024-04-23 07:24 UTC, v61265 commented
> UiHeadingBordered 使用到 <h1> 標籤，然後在一些元件上被重複使用，
例如：UiShowsList，導致整體頁面有不只一個 <h1> 的情況

這確實是一個問題，之後首頁也會需要大量使用，想請教如果改成 h2 可以解決該問題嗎？還是應該比較嚴謹的傳入 priority props 呢？

2024-04-23 10:45 UTC, erase2004 requested changes
> UiHeadingBordered 使用到 <h1> 標籤，然後在一些元件上被重複使用，
> 例如：UiShowsList，導致整體頁面有不只一個 <h1> 的情況

關於這個問題，我的想法是 style 和 sematic 要分開來處理，可以有 title-1 的 class 與其 css style，然後被 h1, p, legend 之類的 HTML element 使用

2024-04-23 10:45 UTC, erase2004 commented on packages/mirror-tv-next/graphql/query/shows.ts
>    sortOrder: number
GraphQL schema 和其 type 的成員沒有批配

2024-04-23 17:37 UTC, v61265 commented on packages/mirror-tv-next/graphql/query/shows.ts
>    sortOrder: number
感謝提醒，已於 [cd27dca](https://github.com/mirror-tv/Tabris/pull/107/commits/cd27dca7f25b768b79536fb165392659584cb21c) 修改。

2024-04-23 17:38 UTC, v61265 commented
> 關於這個問題，我的想法是 style 和 sematic 要分開來處理，可以有 title-1 的 class 與其 css style，然後被 h1, p, legend 之類的 HTML element 使用

我在 [cd27dca](https://github.com/mirror-tv/Tabris/pull/107/commits/cd27dca7f25b768b79536fb165392659584cb21c) 先改了一版，讓該 component 可以決定自己要顯示 h1 還是 h2 還是 h3，這樣應該有符合分開處理？

2024-04-24 05:43 UTC, erase2004 commented
> > 關於這個問題，我的想法是 style 和 sematic 要分開來處理，可以有 title-1 的 class 與其 css style，然後被 h1, p, legend 之類的 HTML element 使用
> 
> 我在 [cd27dca](https://github.com/mirror-tv/Tabris/pull/107/commits/cd27dca7f25b768b79536fb165392659584cb21c) 先改了一版，讓該 component 可以決定自己要顯示 h1 還是 h2 還是 h3，這樣應該有符合分開處理？

style 跟 semantic 還是綁定在一起了，
`ui-heading-bordered.module.scss` 底下的 h1, h2, h3 和同一組 style 綁定在一起，今天增加 p 或 legend 也要用這樣式的話，擴充起來會很麻煩，另外，這種帶 h1 ~ h6 的元件，其實弄成共用元件，其共用性不會太好，因為 h1 ~ h6 有階層的強制性，導致元件沒辦法輕易被擺放，我是建議 heading text style 弄成一組獨立的 CSS style，例如：`heading-text-1`, `heading-text-2`，
要使用時，在引入使用，例如：`<h1 className={styles.head-text-2} />`、`<legend className={styles.heading-text-2} />`

2024-04-24 05:43 UTC, erase2004 reviewed
> > 關於這個問題，我的想法是 style 和 sematic 要分開來處理，可以有 title-1 的 class 與其 css style，然後被 h1, p, legend 之類的 HTML element 使用
> 
> 我在 [cd27dca](https://github.com/mirror-tv/Tabris/pull/107/commits/cd27dca7f25b768b79536fb165392659584cb21c) 先改了一版，讓該 component 可以決定自己要顯示 h1 還是 h2 還是 h3，這樣應該有符合分開處理？

style 跟 semantic 還是綁定在一起了，
`ui-heading-bordered.module.scss` 底下的 h1, h2, h3 和同一組 style 綁定在一起，今天增加 p 或 legend 也要用這樣式的話，擴充起來會很麻煩，另外，這種帶 h1 ~ h6 的元件，其實弄成共用元件，其共用性不會太好，因為 h1 ~ h6 有階層的強制性，導致元件沒辦法輕易被擺放，我是建議 heading text style 弄成一組獨立的 CSS style，例如：`heading-text-1`, `heading-text-2`，
要使用時，在引入使用，例如：`<h1 className={styles.head-text-2} />`、`<legend className={styles.heading-text-2} />`

2024-04-24 06:01 UTC, bibibobobi commented on packages/mirror-tv-next/components/shared/ui-list-posts-aside.tsx
不確定是之後才會用一個 wrapper 把 aside 包住嗎？因為目前的寬度似乎不太正確
![Uploading Screen Shot 2024-04-24 at 1.58.19 PM.png…]()

2024-04-24 06:02 UTC, bibibobobi commented on packages/mirror-tv-next/components/shared/ui-list-posts-aside.tsx
不確定是之後才會用一個 wrapper 把 aside 包住嗎？因為目前的寬度似乎不太正確
<img width="1428" alt="Screen Shot 2024-04-24 at 1 58 19 PM" src="https://github.com/mirror-tv/Tabris/assets/66411169/eeec5aa4-a154-4e9e-958e-074b7a8d8735">

2024-04-24 06:13 UTC, bibibobobi commented on packages/mirror-tv-next/app/category/video/page.tsx
> +  const fetchAllShows = () =>
目前 [header JSON]( https://dev.mnews.tw/json/header_v2.json) 裡面有 allShows 的資料，這邊要不要從 JSON 檔拿？
更進一步也許可以考率把 header JSON 的資料透過 [context API](https://medium.com/@seb_5882/nextjs-13-4-using-context-api-in-app-router-a1198a61c5c8) 傳進來。

2024-04-24 06:15 UTC, bibibobobi commented on packages/mirror-tv-next/components/category/video/ui-show-card.tsx
> +  isArtShow = false,
isArtShow 這個欄位前 PM 表示不需要了，也許可以再跟新 PM 確認一下

2024-04-24 06:17 UTC, bibibobobi commented on packages/mirror-tv-next/components/category/video/ui-show-card.tsx
> +    <a
這邊應該改用 next Link，href 沒有正確傳進來

2024-04-24 06:21 UTC, bibibobobi commented on packages/mirror-tv-next/components/category/video/ui-link-card.tsx
> +            objectFit="contain"
objectFit 已經被棄用，這邊應該改成 `style={{objectFit:"contain"}}`

2024-04-24 09:14 UTC, bibibobobi commented
> > 關於這個問題，我的想法是 style 和 sematic 要分開來處理，可以有 title-1 的 class 與其 css style，然後被 h1, p, legend 之類的 HTML element 使用
> > 
> > 我在 [cd27dca](https://github.com/mirror-tv/Tabris/pull/107/commits/cd27dca7f25b768b79536fb165392659584cb21c) 先改了一版，讓該 component 可以決定自己要顯示 h1 還是 h2 還是 h3，這樣應該有符合分開處理？

> style 跟 semantic 還是綁定在一起了，
> ui-heading-bordered.module.scss 底下的 h1, h2, h3 和同一組 style 綁定在一起，今天增加 p 或 legend 也要用這樣式的話，擴充起來會很麻煩，另外，這種帶 h1 ~ h6 的元件，其實弄成共用元件，其共用性不會太好，因為 h1 ~ h6 有階層的強制性，導致元件沒辦法輕易被擺放，我是建議 heading text style 弄成一組獨立的 CSS style，例如：heading-text-1, heading-text-2，
> 要使用時，在引入使用，例如：`<h1 className={styles.head-text-2} />`、`<legend className={styles.heading-text-2} />`

我的想法是標題的部分統一用 h2 或 p 即可，h1 應該留給 story 頁的文章標題即可，這樣對 SEO 應該比較好？

2024-04-24 10:21 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/ui-show-card.tsx
> +    <a
感謝提醒，已於 [4e88074](https://github.com/mirror-tv/Tabris/pull/107/commits/4e880746ad42864a10d8b5e92b610e1b17d9c028) 修改

2024-04-24 10:21 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/ui-show-card.tsx
> +  isArtShow = false,
感謝提醒，先已於 [4e88074](https://github.com/mirror-tv/Tabris/pull/107/commits/4e880746ad42864a10d8b5e92b610e1b17d9c028) 移除

2024-04-24 14:32 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/ui-link-card.tsx
> +            objectFit="contain"
感謝提醒，我發現因為寬高寫死了他自己會 contain，不用另外加 css 效果一樣，就於 [fd6880f](https://github.com/mirror-tv/Tabris/pull/107/commits/fd6880f7c5aee2766613e2d65d4e028d4cc037db) 移除用不到的 objectFit

2024-04-25 04:18 UTC, v61265 commented
> 我的想法是區塊的標題統一用 h2 或 p 即可，h1 應該留給 story 頁的文章標題，這樣對 SEO 應該比較好？

成交，已於 [29e9677](https://github.com/mirror-tv/Tabris/pull/107/commits/29e96772f2da748a28c01616f1fc62f406d338aa) 修改。

2024-04-25 06:01 UTC, v61265 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +  const fetchAllShows = () =>
我覺得可以，目前先於 [409485e](https://github.com/mirror-tv/Tabris/pull/107/commits/409485eb227a798063c1ed85a09cb0787e313857) 拿 json 資料，之後另外開個 PR 整理目前所有會用到的地方？

2024-04-25 06:06 UTC, erase2004 approved these changes
Accepted 👏

2024-04-25 09:13 UTC, bibibobobi approved these changes
董事長最後的 approval

2024-04-25 13:06 UTC, merged