feat(tv-next): add aside video area of category video page
mirror-tv/Tabris pull request #110
Opened 2024-04-29 07:01 UTC by v61265

### 描述
- 新增影音頁面側欄的 live、即時影音和發燒單元三個區塊。

### 討論
問題：如果讓 youtube autoplay，可以在 devtool 看到他會不斷發 request，必須要手動按暫停才會停止（應該算預期中的狀況）。不過該區塊手機版本和平板版本位置差有點遠，雖然已經用 `aside-video-handler` 管理了，但現在的版本就算在其中一個版本全部按暫停，都還是會繼續發 request。為什麼會有這個現象呢？

2024-04-30 05:31 UTC, erase2004 requested changes
houseVideo 這類別有點抽象，用 otherStreaming 會比較好理解

2024-04-30 05:31 UTC, erase2004 commented on packages/mirror-tv-next/app/action.tsx
`fetchHeaderJson` 似乎還沒被 component 使用？
另外，放在 `app/` 底下，是有其他地方也可能會用到？

2024-04-30 05:31 UTC, erase2004 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +      <AsideVideoListHandler
AsideVideoListHandler 用兩個元件來切分 mobile 還是 desktop 的顯示，會導致說 mobile <-> desktop 切換時，正在播放影片的進度被重設，建議應該使用 CSS order 的方式來處理
ref: https://developer.mozilla.org/en-US/docs/Web/CSS/order

2024-04-30 05:31 UTC, erase2004 commented on packages/mirror-tv-next/components/category/video/aside-video-list-handler.tsx
> +  const isDesktopWidth = useMemo(() => width >= 1200, [width])
Ln. 24 和 Ln. 25 使用 useMemo 其實是多餘的

2024-04-30 05:31 UTC, erase2004 commented on packages/mirror-tv-next/components/category/video/aside-video-list-handler.tsx
> +  const notShown = useMemo(
AsideVideoListHandler 在 `/category/video` 用 CSS order 來調整顯示位置後，isDesktop 和 isMobile 的參數應該就不用了，間接的處理邏輯，如 notShown 或 isDesktopWidth 之類應該也不需要了

2024-04-30 05:31 UTC, erase2004 commented on packages/mirror-tv-next/components/category/video/aside-video-list-handler.tsx
> +          isAutoPlay={!notShown}
不清楚這裡和 notShown 綁定的原因，畢竟能進到這裡，notShown 肯定都是 `false`

2024-05-02 17:43 UTC, v61265 commented
> houseVideo 這類別有點抽象，用 otherStreaming 會比較好理解
感謝提醒，已於 [f3178a7](https://github.com/mirror-tv/Tabris/pull/110/commits/f3178a7c59de9a768b8c0247798db291a8a0156b) 修改

2024-05-02 17:45 UTC, v61265 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +      <AsideVideoListHandler
對耶這也是個問題，感謝提供 order 解法，但 aside 下半部會在主文下方，我暫時想不到 grid 以外比較漂亮的解法，因此在 [f3178a7](https://github.com/mirror-tv/Tabris/pull/110/commits/f3178a7c59de9a768b8c0247798db291a8a0156b) 將重複的段落改成下半部（show 和 share 比較單純）

2024-05-02 17:45 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/aside-video-list-handler.tsx
> +  const isDesktopWidth = useMemo(() => width >= 1200, [width])
對我當時昏頭了 XD 感謝提醒，已經於 [f3178a7](https://github.com/mirror-tv/Tabris/pull/110/commits/f3178a7c59de9a768b8c0247798db291a8a0156b) 都移除掉改由 css 決定。

2024-05-02 17:46 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/aside-video-list-handler.tsx
> +  const notShown = useMemo(
感謝提醒，已於 [f3178a7](https://github.com/mirror-tv/Tabris/pull/110/commits/f3178a7c59de9a768b8c0247798db291a8a0156b) 移除～

2024-05-02 17:47 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/aside-video-list-handler.tsx
> +          isAutoPlay={!notShown}
因為就算我其中一個裝置和暫停，他還是不斷發 request 讓我好害怕，就怕前面沒擋到之類的所以先加（？）不過目前已於 [f3178a7](https://github.com/mirror-tv/Tabris/pull/110/commits/f3178a7c59de9a768b8c0247798db291a8a0156b) 用 css 改進該問題。

2024-05-02 17:48 UTC, v61265 commented on packages/mirror-tv-next/app/action.tsx
不好意思這是不小心混到的，已於 [fc75116](https://github.com/mirror-tv/Tabris/pull/110/commits/fc75116277d0803df8a594e8aa4422b0ae528df5) 移除，感謝提醒！

2024-05-06 02:39 UTC, erase2004 reviewed
請問有沒有設計稿？我需要釐清 category video page 的設計，謝謝

2024-05-06 02:39 UTC, erase2004 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +    'Error occurs while fetching house videos in video category page'
error message 也要調整

2024-05-06 04:39 UTC, v61265 commented
figma 在這裏：https://www.figma.com/file/BATB1ux8KjfWYa4DV1Xm3t/2024_%E9%8F%A1%E9%9B%BB%E8%A6%96_Web?node-id=0-3456&mode=dev

2024-05-06 04:42 UTC, v61265 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +    'Error occurs while fetching house videos in video category page'
感謝提醒，已於 [6cb1f75](https://github.com/mirror-tv/Tabris/pull/110/commits/6cb1f752c2b88ee0de662b64a49d6e8eb82db122) 修改

2024-05-06 05:12 UTC, erase2004 reviewed
節目區塊在 mobile 下的顯示是有問題的。
<img width="934" alt="Snipaste_2024-05-06_13-11-46" src="https://github.com/mirror-tv/Tabris/assets/1367757/6279abd8-1456-4edc-8d52-11273cfcce7c">

2024-05-06 05:20 UTC, v61265 commented
> 節目區塊在 mobile 下的顯示是有問題的。

抱歉忘記說明，這裡應該由之後的廣告單元撐開 ><

2024-05-06 05:30 UTC, v61265 commented
先在 [ee73608](https://github.com/mirror-tv/Tabris/pull/110/commits/ee736089341936e8cc9fd6a99f5a0cbd0e46b007) 加上簡單間距

2024-05-06 07:19 UTC, erase2004 commented on packages/mirror-tv-next/styles/components/category/video/ui-show-cards-list.module.scss
> +  margin-top: 53px;
應該是 48px?

2024-05-06 07:44 UTC, v61265 commented on packages/mirror-tv-next/styles/components/category/video/ui-show-cards-list.module.scss
> +  margin-top: 53px;
感謝提醒，已於 [621db40](https://github.com/mirror-tv/Tabris/pull/110/commits/621db40ee262eaa8b5ffa512595a6496b4ab59e7) 修改

2024-05-06 08:18 UTC, erase2004 approved these changes
LGTM 👏

2024-05-06 08:30 UTC, merged