feat(tv-next): add editor-choice-video of video page
mirror-tv/Tabris pull request #115
Opened 2024-05-08 05:10 UTC by v61265

### 描述
- 新增影音頁「編輯精選」區塊。
- 不同文章間五秒輪播，若按開始播放則暫停輪播，影片結束後才會繼續輪播。
- 為了方便事件監聽，將 youtube embed 改用套件 `react-youtube`。

### 參考資料
- [figma](https://www.figma.com/design/BATB1ux8KjfWYa4DV1Xm3t/2024_%E9%8F%A1%E9%9B%BB%E8%A6%96_Web?node-id=0-3456&m=dev)
- [1.0 頁面](https://dev.mnews.tw/category/video)

2024-05-08 07:42 UTC, erase2004 requested changes
`YoutubeEmbed` 在 `EditorChoiceVideoList` 的使用上，應該多套一層 DOM element，這樣在 desktop 以上的情況下，抓到的 padding-bottom 的參考不會是整頁寬，而是上層元素的寬度，這樣應該可以簡化 EditorChoiceVideoList#feature 的 style

順道一題，`*.module.scss` 是否考慮開始與對應的 page 或 component 放在同一個目錄底下？

2024-05-08 07:42 UTC, erase2004 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +    'Error occurs while fetching video category page in video category page'
這錯誤敘述詭異， `video category page in video category page` ?

2024-05-08 07:42 UTC, erase2004 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +      console.log(data?.data?.allVideoEditorChoices)
應該移除

2024-05-08 07:42 UTC, erase2004 commented on packages/mirror-tv-next/components/category/video/editor-choice-video-list.tsx
> +      if (prev + 1 > videoLists.length - 1) return 0
應該用 `return (prev + 1) % videoLists.length` 就好了

2024-05-08 07:42 UTC, erase2004 commented on packages/mirror-tv-next/components/category/video/editor-choice-video-list.tsx
> +  }, [status])
這裡有 warning，參考
https://react.dev/reference/react/useEffect#removing-unnecessary-function-dependencies

2024-05-08 07:42 UTC, erase2004 commented on packages/mirror-tv-next/components/category/video/editor-choice-video-list.tsx
> +      clearInterval(timer!)
需要加上 `!` 的原因？

2024-05-08 07:42 UTC, erase2004 commented on packages/mirror-tv-next/components/category/video/editor-choice-video-list.tsx
> +    return () => clearInterval(timer!)
需要加上 `!` 的原因？

2024-05-08 07:42 UTC, erase2004 commented on packages/mirror-tv-next/components/shared/youtube-embed.tsx
> +  handleEnded?: () => void
應該直接用 `YouTubeProps` 上的 type

2024-05-08 07:42 UTC, erase2004 commented on packages/mirror-tv-next/components/shared/youtube-embed.tsx
> +  handlePlaying?: () => void
應該直接用 `YouTubeProps` 上的 type

2024-05-08 07:42 UTC, erase2004 commented on packages/mirror-tv-next/components/shared/youtube-embed.tsx
> +  handleEnded = () => {},
default 的 `() => {}` 應該不需要?

2024-05-08 07:42 UTC, erase2004 commented on packages/mirror-tv-next/components/shared/youtube-embed.tsx
> +  handlePlaying = () => {},
default 的 `() => {}` 應該不需要?

2024-05-08 07:42 UTC, erase2004 commented on packages/mirror-tv-next/graphql/query/video-editor-choice.ts
> +  videoEditor: {
可能是 null 的值應該加上 null type

2024-05-08 07:42 UTC, erase2004 commented on packages/mirror-tv-next/styles/components/category/video/editor-choices.module.scss
在 tablet 大小，依照設計稿，有最高高度，且超過時會有 scroll 的設計
![Snipaste_2024-05-08_15-29-18](https://github.com/mirror-tv/Tabris/assets/1367757/6411eb28-fd72-43bd-b4ef-feb39182d7bf)

2024-05-08 07:42 UTC, erase2004 commented on packages/mirror-tv-next/styles/components/category/video/editor-choices.module.scss
> +.container {
建議在 container 這一層就把寬度撐滿，這樣下層操作會比較單純
![Snipaste_2024-05-08_15-32-21](https://github.com/mirror-tv/Tabris/assets/1367757/72aec0dc-a4ef-4762-9b7d-d802c54fa909)

2024-05-08 07:42 UTC, erase2004 commented on packages/mirror-tv-next/styles/components/category/video/editor-choices.module.scss
> +  height: calc((100% + 40px) * 0.5625);
不建議直接用 0.5625，如果是 `9 / 16` 的話，直接用 `9 / 16`，這樣語意上比較清楚

2024-05-10 05:19 UTC, v61265 commented on packages/mirror-tv-next/styles/components/category/video/editor-choices.module.scss
> +  height: calc((100% + 40px) * 0.5625);
感謝說明，已於 [2a165e7](https://github.com/mirror-tv/Tabris/pull/115/commits/2a165e77226cf3f09087338c72352d035c0f6928) 修改

2024-05-10 05:20 UTC, v61265 commented on packages/mirror-tv-next/styles/components/category/video/editor-choices.module.scss
感謝提醒，已於 [2a165e7](https://github.com/mirror-tv/Tabris/pull/115/commits/2a165e77226cf3f09087338c72352d035c0f6928) 修改！

2024-05-10 05:20 UTC, v61265 commented on packages/mirror-tv-next/components/shared/youtube-embed.tsx
> +  handlePlaying = () => {},
感謝提醒，已於 [2a165e7](https://github.com/mirror-tv/Tabris/pull/115/commits/2a165e77226cf3f09087338c72352d035c0f6928) 修改。

2024-05-10 05:20 UTC, v61265 commented on packages/mirror-tv-next/components/shared/youtube-embed.tsx
> +  handleEnded = () => {},
感謝提醒，已於 [2a165e7](https://github.com/mirror-tv/Tabris/pull/115/commits/2a165e77226cf3f09087338c72352d035c0f6928) 修改

2024-05-10 05:20 UTC, v61265 commented on packages/mirror-tv-next/components/shared/youtube-embed.tsx
> +  handlePlaying?: () => void
感謝提醒，已於 [2a165e7](https://github.com/mirror-tv/Tabris/pull/115/commits/2a165e77226cf3f09087338c72352d035c0f6928) 修改

2024-05-10 05:22 UTC, v61265 commented on packages/mirror-tv-next/components/shared/youtube-embed.tsx
> +  handleEnded?: () => void
className 那一行應該是多標到的？因為目前的 className 是給外層的 div 使用，所以應該不用使用 `YouTubeProps` 的 type。
另外 handleEnded 已於 [2a165e7](https://github.com/mirror-tv/Tabris/pull/115/commits/2a165e77226cf3f09087338c72352d035c0f6928) 修改

2024-05-10 05:22 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/editor-choice-video-list.tsx
> +      if (prev + 1 > videoLists.length - 1) return 0
感謝說明，長知識！已於 [2a165e7](https://github.com/mirror-tv/Tabris/pull/115/commits/2a165e77226cf3f09087338c72352d035c0f6928) 修改～

2024-05-10 05:22 UTC, v61265 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +      console.log(data?.data?.allVideoEditorChoices)
感謝提醒，已於 [2a165e7](https://github.com/mirror-tv/Tabris/pull/115/commits/2a165e77226cf3f09087338c72352d035c0f6928) 修改

2024-05-10 05:23 UTC, v61265 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +    'Error occurs while fetching video category page in video category page'
感謝提醒，已於 [2a165e7](https://github.com/mirror-tv/Tabris/pull/115/commits/2a165e77226cf3f09087338c72352d035c0f6928) 修改

2024-05-10 05:41 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/editor-choice-video-list.tsx
> +  }, [status])
不好意思我好像沒有安裝顯示 warning，想請教你那邊的設定或是 extention，感謝！
另外不太確定該 warning 和參考資料之間的關係。我目前加上 console 觀測，除了一開始會觸發兩次外，之後除了開始播放和影片結束（status 有改變）以外皆不會觸發該 useEffect。
<img width="693" alt="截圖 2024-05-10 下午1 33 45" src="https://github.com/mirror-tv/Tabris/assets/66636137/0645cdfd-6c82-481e-ab45-2c054f40e533">

2024-05-12 09:22 UTC, v61265 commented on packages/mirror-tv-next/styles/components/category/video/editor-choices.module.scss
> +.container {
感謝建議，已於 [4ba18f4](https://github.com/mirror-tv/Tabris/pull/115/commits/4ba18f49a31ca414c75a6010287057a2bb4ab656) 修改（順便微調其他 UI）

2024-05-12 09:24 UTC, v61265 commented on packages/mirror-tv-next/graphql/query/video-editor-choice.ts
> +  videoEditor: {
感謝提醒，已於 [4ba18f4](https://github.com/mirror-tv/Tabris/pull/115/commits/4ba18f49a31ca414c75a6010287057a2bb4ab656) 修改

2024-05-12 09:24 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/editor-choice-video-list.tsx
> +      clearInterval(timer!)
本來是因為會跳 error 才加的，但調整過後已經不需要 `!` 了，故在 [4ba18f4](https://github.com/mirror-tv/Tabris/pull/115/commits/4ba18f49a31ca414c75a6010287057a2bb4ab656) 移除，感謝提醒

2024-05-12 09:36 UTC, v61265 commented
> 順道一題，*.module.scss 是否考慮開始與對應的 page 或 component 放在同一個目錄底下？

我也覺得檔案一大就頭昏眼花，想請教是指像 [d8cf95e](https://github.com/mirror-tv/Tabris/pull/115/commits/d8cf95e4dc0ed6ea7b1203ced5501ccd61ac2445) 這樣放嗎？

2024-05-12 09:50 UTC, v61265 commented
> YoutubeEmbed 在 EditorChoiceVideoList 的使用上，應該多套一層 DOM element，這樣在 desktop 以上的情況下，抓到的 padding-bottom 的參考不會是整頁寬，而是上層元素的寬度，這樣應該可以簡化 EditorChoiceVideoList#feature 的 style

感謝提醒，已於 [a6b76d2](https://github.com/mirror-tv/Tabris/pull/115/commits/a6b76d2d58b7556a22cb6f2b572a9a963c8fcf58) 調整～

2024-05-13 11:51 UTC, erase2004 reviewed
1. 位置
2. 框內區域的大小，與頁面邊緣的距離；mobile 底下，應該沒有高度限制？
3. 按鈕更換樣式了？與 1.0 不同
![Snipaste_2024-05-13_19-19-48](https://github.com/mirror-tv/Tabris/assets/1367757/cc70a002-0c54-4273-8385-afa364cf236a)

另外發現的問題：
https://github.com/mirror-tv/Tabris/issues/121

2024-05-13 11:51 UTC, erase2004 commented on packages/mirror-tv-next/components/category/video/editor-choice-video-list.tsx
> +  }, [status])
![Snipaste_2024-05-13_19-04-03](https://github.com/mirror-tv/Tabris/assets/1367757/0f87a880-5af4-4c5b-a6e2-df425429650f)

2024-05-13 11:51 UTC, erase2004 commented on packages/mirror-tv-next/graphql/query/video-editor-choice.ts
> +  videoEditor: {
沒有加完全

2024-05-15 04:21 UTC, v61265 commented
> 沒有加完全

感謝提醒，已於 [e591af7](https://github.com/mirror-tv/Tabris/pull/115/commits/e591af7fe593dbab6c2f26a913d2cae9694d26ee) 補上

2024-05-15 04:27 UTC, v61265 commented
- dependency 問題已於 [ee96455](https://github.com/mirror-tv/Tabris/pull/115/commits/ee964554f00d56326db4e99ae93697ecffc75286) 補上。
- 第一點、第二點也於 [ee96455](https://github.com/mirror-tv/Tabris/pull/115/commits/ee964554f00d56326db4e99ae93697ecffc75286) 調整了。
- 第三點之前有和 nini 跟設計師討論過全站 video icon 統一，之後應該要 refactor 到 global style 裡面！（應該會另開 PR）

2024-05-15 10:29 UTC, erase2004 reviewed
1. 這尺寸以上，應該有高度限制？
![Snipaste_2024-05-15_18-23-42](https://github.com/mirror-tv/Tabris/assets/1367757/9e6f026a-c051-4692-b2ac-31c7d7ae99fd)
2. 這算 https://github.com/mirror-tv/Tabris/issues/121 的一部分，在 1200 以上，左邊界沒有對齊
![Snipaste_2024-05-15_18-26-14](https://github.com/mirror-tv/Tabris/assets/1367757/b70dfa6f-f2b9-4630-97ad-0171846f5347)

2024-05-15 17:03 UTC, v61265 commented
1.
目前參考 [1.0 網站](https://dev.mnews.tw/category/video) （可見附圖）在 768 ~ 1200px 下沒有針對高度做限制。
<img width="1827" alt="截圖 2024-05-16 凌晨12 49 47" src="https://github.com/mirror-tv/Tabris/assets/66636137/4e2ac39d-1b3a-470d-80f7-dfb1ebb7afc2">

2.
感謝提醒，已於 [6ea493c](https://github.com/mirror-tv/Tabris/pull/115/commits/6ea493ca3d40454b7c2818d215d45eed9dfcd32f) 修改。

2024-05-16 05:17 UTC, erase2004 approved these changes
Approved 👏

2024-05-16 06:47 UTC, merged