feat(tv-next): UI of search page
mirror-tv/Tabris pull request #125
Opened 2024-06-17 04:43 UTC by LinHeMa

## 描述

- [ ] 需要更換正式的search engine

## 參考資料
[figma](https://www.figma.com/design/BATB1ux8KjfWYa4DV1Xm3t/2024_%E9%8F%A1%E9%9B%BB%E8%A6%96_Web?node-id=0-12393&t=ONw3Y9hIwaOYiIzf-0)
[1.0 頁面](https://staging.mnews.tw/search/%E6%B8%AC%E8%A9%A6)

2024-06-17 11:03 UTC, erase2004 reviewed
* type 命名應該用大寫開頭
* 資料有 nullable 的情況下，定義的 type 應當使用 `?` 或 `| null`，而不是在使用端硬套上 optional chaining，例如：
  ```TypeScript
  // This is not okay
  type Data = {
    key1: string
    key2: string
  }

  someFunction(data?.key1 ?? '') // typeof `data` is Data
  ```
應該調整為
```TypeScript
// This is okay
type Data = {
  key1?: string
  key2: string | null
}

someFunction(data?.key1 ?? '') // typeof `data` is Data
```
* css classname 的命名規則不一致，有用 kebeb case，也有用 camel case 的情況，需要統一 cc @v61265

2024-06-17 11:03 UTC, erase2004 commented on packages/mirror-tv-next/app/search/[keyword]/page.tsx
> +import {
import type

2024-06-17 11:03 UTC, erase2004 commented on packages/mirror-tv-next/app/search/[keyword]/page.tsx
> +      popularResultList = onlyShow4Results(popularResultResponse?.report) || []
應該可以參考 Ui404 的處理邏輯，來產生正確的 popularResultList 資料

2024-06-17 11:03 UTC, erase2004 commented on packages/mirror-tv-next/app/search/[keyword]/page.tsx
> +      width: 166,
width 和 height 當作 props 傳入似乎是多餘的

2024-06-17 11:03 UTC, erase2004 commented on packages/mirror-tv-next/app/search/[keyword]/page.tsx
> +  const searchResultProps = {
只在 Ln. 72 被使用，應當放到 Ln. 72 附近

2024-06-17 11:03 UTC, erase2004 commented on packages/mirror-tv-next/components/layout/header/header-search-bar.tsx
> +      <button className={styles.searchButton}>
按鈕點擊後，應該要有跳轉到搜尋頁的處理？

2024-06-17 11:03 UTC, erase2004 commented on packages/mirror-tv-next/components/search/search-no-result.tsx
應該調整命名為 `NoSearchResult`

2024-06-17 11:03 UTC, erase2004 commented on packages/mirror-tv-next/components/search/search-result.tsx
> +import { TVPost } from '~/types/api-data'
import type

2024-06-17 11:03 UTC, erase2004 commented on packages/mirror-tv-next/components/search/search-result.tsx
> +import UiPostCard, { UiPostCardProps } from '~/components/shared/ui-post-card'
type UiPostCardProps

2024-06-18 03:53 UTC, LinHeMa commented
> css classname 的命名規則不一致，有用 kebeb case，也有用 camel case 的情況，需要統一 cc @v61265

這邊是指code裡面有還是說我這次的commit？
我的理解是目前SCSS檔案中的className應該都是用kebeb case

2024-06-18 04:19 UTC, erase2004 commented
> > css classname 的命名規則不一致，有用 kebeb case，也有用 camel case 的情況，需要統一 cc @v61265
> 
> 這邊是指code裡面有還是說我這次的commit？ 我的理解是目前SCSS檔案中的className應該都是用kebeb case

電視專案應該有自己的 Convention，不然類似的問題會在發生，可以參考 Mesh 的[範例](https://paper.dropbox.com/doc/Conventions--CRTDo~ebU1bUF1MXbZtKEFJxAg-yYpojrBoPnXFasvo29Yiu) 來訂立屬於此專案的 Convention
cc @v61265

2024-06-18 04:21 UTC, erase2004 commented
另外，
1. commit message 加上 emoji 是多餘且無用的資訊，請在後續移除
2. 調整完需要再次 review，請點擊下圖所示按鈕
![Snipaste_2024-06-18_12-20-57](https://github.com/mirror-tv/Tabris/assets/1367757/55a9bb30-4c5e-488a-bcbe-353d0294d1d4)

2024-06-18 06:08 UTC, v61265 commented
我來了！！！
目前 className 命名有兩種，是因為他們針對不同功用：
1. camel case：用於 scss module，因為他不吃 kebeb case，統一用於實際寫 style。
2. kebeb case：用於和 GTM 捕捉事件，詳細可參考 [這份文件](https://paper.dropbox.com/doc/Mirror-TV-GA4-Events--CRRT~NKKayjlDMi5KSyiN6YYAg-7KlQYLfpoR69i4qpUsTX4)。如果要改成 camel case 也不是不行，但就要統一讓 PM 那邊一起更改 GTM 設定，而且每個環境都要改一次。我傾向不更改，也方便工程師辨認不會誤刪。
只是不確定以上這些是否需要加在 readme 或哪份文件內嗎？

2024-06-19 01:15 UTC, erase2004 commented
> 我來了！！！ 目前 className 命名有兩種，是因為他們針對不同功用：
> 
>     1. camel case：用於 scss module，因為他不吃 kebeb case，統一用於實際寫 style。
> 
>     2. kebeb case：用於和 GTM 捕捉事件，詳細可參考 [這份文件](https://paper.dropbox.com/doc/Mirror-TV-GA4-Events--CRRT~NKKayjlDMi5KSyiN6YYAg-7KlQYLfpoR69i4qpUsTX4)。如果要改成 camel case 也不是不行，但就要統一讓 PM 那邊一起更改 GTM 設定，而且每個環境都要改一次。我傾向不更改，也方便工程師辨認不會誤刪。
> 
> 
> 只是不確定以上這些是否需要加在 readme 或哪份文件內嗎？

參考 MeshWeb 或鏡報的範例，在專案索引資料夾建立索引文件，裡面放上 TV 相關文件的連結，至於 TV 相關工程文件，可以統一放到一個資料夾底下做管理，在這資料夾底下，你就可以參考 MeshWeb 或鏡報的模式，存放一個文件是用來記錄 Convention，你就把這資訊放到 Convention 當中 cc @v61265

2024-06-19 02:12 UTC, erase2004 commented on packages/mirror-tv-next/app/search/[keyword]/page.tsx
> +import React from 'react'
多餘的

2024-06-19 02:12 UTC, erase2004 commented on packages/mirror-tv-next/types/api-data.ts
> +type _sourceType = {
(再次強調) type 命名應該用大寫開頭

2024-06-19 02:12 UTC, erase2004 commented on packages/mirror-tv-next/types/api-data.ts
type 或 interface 交互使用，應考慮統一使用 `type`

2024-06-19 02:12 UTC, erase2004 commented on packages/mirror-tv-next/app/search/[keyword]/page.tsx
> +  console.log(keyword)
開發用的 console.log 應當移除

2024-06-19 02:12 UTC, erase2004 commented on packages/mirror-tv-next/components/search/no-search-result.tsx
> +const SearchNoResult = ({ keyword }: SearchNoResultProps) => {
檔名改了，但元件名稱沒改

2024-06-19 02:12 UTC, erase2004 commented on packages/mirror-tv-next/components/search/no-search-result.tsx
> +  const formattedPostsCount = isDesktop ? 4 : 3
應該在 desktop_1200 以上才顯示 4 筆

2024-06-19 02:12 UTC, erase2004 commented on packages/mirror-tv-next/components/search/no-search-result.tsx
> +  useEffect(() => {
可以嘗試把抓取資料的部份在 server-side 執行，而非在 client-side 再抓取，然後把使用到 hook 的部份，用另一個 compoent 來管理，把 data fetching 和 client view 分離開來

2024-06-19 02:12 UTC, erase2004 commented on packages/mirror-tv-next/components/layout/header/header-search-bar.tsx
> +        <button className={styles.searchButton}>
可以把 searchButton 的 style 綁到 parent Link 上，移除多餘的 `<button />`

2024-06-19 05:38 UTC, LinHeMa commented
已新增文件到dropbox，目前只有把GTM的地方補上，其他部分待補。

2024-06-19 07:21 UTC, erase2004 reviewed
`PopularList` 的資料抓取放到 page 的解法尚可，但還可以更好
可以把 `NoSearchResult` 轉為 server component，在當中抓取 `PopularList` 的資料，
然後把需要用到 hook 的部份，額外交給一個 client component 處理，
畢竟 PopularList 的資料只有 `NoSearchResult` 有用到，在 page 層抓取，
反而會在顯示 `SerachResult` 的情況下，造成浪費。

2024-06-19 07:21 UTC, erase2004 commented on packages/mirror-tv-next/README.md
> +請見此[Document](https://paper.dropbox.com/doc/Conventions--CRV1VF0ZmlU4yOPOlpCdnKJUAQ-Y5dSxqXJ16cTuQlOgg6LB)
應該要導向至放在 `13. 專案索引專區` 底下的索引文件

2024-06-19 07:21 UTC, erase2004 commented on packages/mirror-tv-next/types/api-data.ts
> +import { HeroImage } from './common'
import type

2024-06-19 08:47 UTC, erase2004 approved these changes
功能面，這邊看起來是 ok 的，
剩下看 @v61265 那邊接手處理的意見了

2024-06-24 08:14 UTC, v61265 requested changes

2024-06-24 08:14 UTC, v61265 commented on packages/mirror-tv-next/app/search/[keyword]/page.tsx
> +  if (searchResultList.length === 0) return <NoSearchResult keyword={keyword} />
是不是可以不用 `===0`，畢竟 0 本來就是 falsy 值

2024-06-24 08:14 UTC, v61265 commented on packages/mirror-tv-next/components/layout/header/mobile-header/search-bar.tsx
> +  const searchIconStyle = isSearchBarShown
nit：雖然也和 style 有關，但是先牽扯到 className，如果是我的話會命名 searchIconClassName 比較直覺。

2024-06-24 08:14 UTC, v61265 commented on packages/mirror-tv-next/components/layout/header/mobile-header/_styles/search-bar.module.scss
> +  .searchIcon {
目前在桌機版點擊 icon 會有 button 預設的 outline，可以在 focus 時用 `outline: none`～

2024-06-24 08:14 UTC, v61265 commented on packages/mirror-tv-next/components/search/_styles/no-search-result.module.scss
> +  --borderWidth: 3px;
這個寫法讚讚 👍

2024-06-24 08:14 UTC, v61265 commented on packages/mirror-tv-next/components/layout/header/mobile-header/search-bar.tsx
> +  const searchIconStyle = isSearchBarShown
偷偷很菜的詢問一下：為什麼沒有掛 useMemo 決定 dependecy，卻可以根據 isSearchBarShown 做出更動 ><

2024-06-24 08:14 UTC, v61265 commented on packages/mirror-tv-next/components/search/search-result.tsx
> +              images: {
可以參考現成的 `/utils/image-handler` 中的 `formateHeroImage` 直接使用

2024-06-24 08:14 UTC, v61265 commented on packages/mirror-tv-next/components/search/no-search-result.tsx
> +      images: formatePostImage(articleCardList as PostCardItem),
（對不起我的鍋）因為 formatePostImage 太難用了，我會再找時間全部改成 formateHeroImage，這裡要改不改都可以 XD

2024-06-24 08:14 UTC, v61265 commented on packages/mirror-tv-next/components/search/search-result.tsx
> +        <button className={styles.seeMoreBtn}>看更多</button>
nit: 可以用現成 `/components/shared/ui-load-more-button.tsx`，之前和 PM 確認過所有地方的看更多都一樣樣是沒關係。

2024-06-25 01:40 UTC, LinHeMa commented on packages/mirror-tv-next/components/layout/header/mobile-header/search-bar.tsx
> +  const searchIconStyle = isSearchBarShown
quote: [https://www.joshwcomeau.com/react/why-react-re-renders/](example)
因為 `isSearchBarShown` 是一個state，因此當它透過`setState`被更新會觸發re-render的機制。
而這個機制會使這個component以及他的children re-render。

2024-06-25 01:43 UTC, LinHeMa commented on packages/mirror-tv-next/components/search/no-search-result.tsx
> +      images: formatePostImage(articleCardList as PostCardItem),
那我這裡先不改，掛個FIXME

2024-06-26 16:49 UTC, v61265 commented on packages/mirror-tv-next/components/layout/header/mobile-header/search-bar.tsx
> +  const searchIconStyle = isSearchBarShown
感謝貼心說明，並且耐心解決我的困惑 orz
是時候再讀一次文件了！（我是說我）

2024-06-26 16:49 UTC, v61265 commented on packages/mirror-tv-next/components/search/no-search-result.tsx
> +      images: formatePostImage(articleCardList as PostCardItem),
ok 沒問題！

2024-06-26 16:52 UTC, v61265 approved these changes
除了一個小小 css 問題外 LGTM。但可能要麻煩你先 pending 不要 merge，我這兩天和 PM 確認一下會不會影響分批 migrate 進正式機的流程。

2024-06-26 16:52 UTC, v61265 commented on packages/mirror-tv-next/components/layout/header/mobile-header/_styles/search-bar.module.scss
> +  .searchIcon {
不好意思一開始沒說清楚，focus 的寫法是：
```css
&:focus {
  outline: none;
}
```

2024-07-04 17:43 UTC, merged