feat(tv): add tag page without loadmore
mirror-tv/Tabris pull request #29
Opened 2024-01-17 16:31 UTC by v61265

### 描述
新增 tag 頁面。
<img width="1231" alt="截圖 2024-01-18 凌晨12 29 38" src="https://github.com/mirror-tv/Tabris/assets/66636137/d4f1893f-63b3-4bc5-ba32-2647565b4863">

### 待討論點
1. type 需要集中管理嗎？

2024-01-18 04:53 UTC, erase2004 reviewed
初步看一下，但看到比較明顯的問題，這些問題未必和此 PR 有關，但還是先做回報：
1. graphql query / mutation 不是用動詞 + 名詞的型式命名，以 `postsByTagName` 為例，應該命名為 `getPostsByTageName`
2. README 沒有目錄結構說明，目前看起來沒有存放 type 使用的目錄，所以不確定 type 是想要用什麼方式管理
3. 檔案命名有問題，這裡看起來都是使用 `kebab-case`，但在 `listingPost` 卻違反了這個原則
4. `/public/default` 如果底下是來拿放 image 或 svg icon 的話，建議改用 `/public/images` 和 `/public/icons` 的形式

2024-01-18 04:53 UTC, erase2004 commented on packages/mirror-tv-next/@readr-media/react-image.d.ts
這個套件應該有輸出 type 了，所以使用方不用再自行定義了

2024-01-18 09:27 UTC, bibibobobi commented
<img width="923" alt="Screen Shot 2024-01-18 at 5 08 35 PM" src="https://github.com/mirror-tv/Tabris/assets/66411169/00eb5534-5d38-4776-994b-093064cb3b67">
<img width="904" alt="Screen Shot 2024-01-18 at 5 08 20 PM" src="https://github.com/mirror-tv/Tabris/assets/66411169/db1705e7-2510-4003-a19c-7eabb8cbb56a">
tablet 尺寸頁面沒有 padding，卡片上下排也沒對齊。
因為 css calc 蠻耗效能的，建議是固定卡片寬度，使用 grid system 去做佈局，可以參考週刊這種寫法：

```
const CardsWrapper = styled.ul` display: grid; row-gap: 20px;
${({ theme }) => theme.breakpoint.md} {
grid-template-columns: 1fr 1fr;
grid-gap: 28px;
gap: 28px;
}
${({ theme }) => theme.breakpoint.xl} {
grid-template-columns: 1fr 1fr 1fr 1fr;
row-gap: 28px;
column-gap: 16px;
}
```

2024-01-18 13:28 UTC, bibibobobi commented on packages/mirror-tv-next/components/shared/ui-post-card.tsx
> +  // 限制 brief 字數
限制 brief 字數應該用 CSS  -webkit-line-clamp 去處理就可以了？postDescriptionTruncated 這個 function會做很多不必要的運算

2024-01-18 13:34 UTC, bibibobobi commented on packages/mirror-tv-next/components/shared/ui-post-card.tsx
> +            <span className="g-video-news-img-icon-wrapper">
這個 className 是有用到的嗎？

2024-01-18 13:38 UTC, bibibobobi requested changes

2024-01-18 13:38 UTC, bibibobobi commented on packages/mirror-tv-next/components/shared/ui-post-card.tsx
> +              <span className="g-video-news-img-icon" />
這個似乎也沒用到

2024-01-18 13:43 UTC, bibibobobi commented on packages/mirror-tv-next/styles/pages/tag.module.scss
> +  @include breakpoint(xxl) {
目前設計稿似乎還沒有看到 xxl 的樣式

2024-01-18 13:48 UTC, bibibobobi commented on packages/mirror-tv-next/app/tag/[name]/page.tsx
> +import tagStyles from '~/styles/pages/tag.module.scss'
這邊要不要統一用 import **styles** from

2024-01-18 13:55 UTC, bibibobobi commented on packages/mirror-tv-next/styles/pages/tag.module.scss
建議命名為 tag-page.module.scss

2024-01-18 14:24 UTC, bibibobobi commented on packages/mirror-tv-next/app/tag/[name]/page.tsx
App router 有一個需要特別注意的地方是，如果沒有設定 revalidate 的時間，資料就會一生一世被 cache 住，詳情可以讀這篇文章，https://www.apollographql.com/blog/how-to-use-apollo-client-with-next-js-13，所以這邊需要加上 export const revalidate = GLOBAL_CACHE_SETTING; （我有先在環境變數設定了時間，之後可以再視情況調整）

2024-01-18 14:51 UTC, bibibobobi commented on packages/mirror-tv-next/public/default/image-default.jpg
這張圖應該移到 /public/images 資料夾，並刪除 default 資料夾

2024-01-18 14:51 UTC, bibibobobi commented on packages/mirror-tv-next/public/default/loading.svg
同上

2024-01-19 06:39 UTC, v61265 commented on packages/mirror-tv-next/public/default/loading.svg
已於 [21159b8](https://github.com/mirror-tv/Tabris/pull/29/commits/21159b84097295c7e87bb1ee76b882ddcfa1d044) 修改

2024-01-19 06:39 UTC, v61265 commented on packages/mirror-tv-next/public/default/image-default.jpg
了解！已於 [21159b8](https://github.com/mirror-tv/Tabris/pull/29/commits/21159b84097295c7e87bb1ee76b882ddcfa1d044) 修改

2024-01-19 06:43 UTC, v61265 commented on packages/mirror-tv-next/app/tag/[name]/page.tsx
> +import tagStyles from '~/styles/pages/tag.module.scss'
ok，已於 [7ef981a](https://github.com/mirror-tv/Tabris/pull/29/commits/7ef981a5658dfa9497d648084bb565d8d632d16c) 修改

2024-01-19 06:43 UTC, v61265 commented on packages/mirror-tv-next/styles/pages/tag.module.scss
感謝提醒，已於 [7ef981a](https://github.com/mirror-tv/Tabris/pull/29/commits/7ef981a5658dfa9497d648084bb565d8d632d16c) 修改

2024-01-19 06:51 UTC, v61265 commented on packages/mirror-tv-next/app/tag/[name]/page.tsx
重要資訊！感謝提醒，已於 [341648b](https://github.com/mirror-tv/Tabris/pull/29/commits/341648b02e4c268d528e50f034d21643752e3cf5) 修改～

2024-01-19 09:30 UTC, v61265 commented on packages/mirror-tv-next/@readr-media/react-image.d.ts
感謝提醒 + 附帶 debug 和解說，已於 [3231335](https://github.com/mirror-tv/Tabris/pull/29/commits/3231335f62458dd77720004629dec924be528a51) 修改

2024-01-19 09:34 UTC, v61265 commented on packages/mirror-tv-next/@readr-media/react-image.d.ts
另外上面四點，第一點和第三點已於 [18963d2](https://github.com/mirror-tv/Tabris/pull/29/commits/18963d25a2c265f0d2e206c7d8f82cc21e832468) 修改，第四點已於 [21159b8](https://github.com/mirror-tv/Tabris/pull/29/commits/21159b84097295c7e87bb1ee76b882ddcfa1d044) 修改，感謝說明！

2024-01-20 03:41 UTC, v61265 commented on packages/mirror-tv-next/components/shared/ui-post-card.tsx
> +  // 限制 brief 字數
這邊抄 1.0 的 XD 不過目前 tag 頁使用它時並沒有 description 功能，看 1.0 只有搜尋結果會用到 `description`，但頁面上又沒有出現相對應內容 🤔 可能等禮拜一來問問 PM 的需求，如果連 search 頁面都不需要的話，也許可以整個拿掉 www

2024-01-21 15:23 UTC, v61265 commented on packages/mirror-tv-next/styles/pages/tag.module.scss
> +  @include breakpoint(xxl) {
我是看這一份：https://www.figma.com/file/BATB1ux8KjfWYa4DV1Xm3t/mmtv?node-id=1064%3A44070&mode=dev

2024-01-21 15:27 UTC, v61265 commented on packages/mirror-tv-next/components/shared/ui-post-card.tsx
> +              <span className="g-video-news-img-icon" />
對齁忘了寫到這兩個，照理來說應該要，因為現在 nuxt 版本有兩種 video icon 設計，明天和 PM 確認後再修改，十分感謝提醒 orz

2024-01-21 15:30 UTC, v61265 commented on packages/mirror-tv-next/components/shared/ui-post-card.tsx
> +              <span className="g-video-news-img-icon" />
另外，最上面提到 post wrapper 的寫法已經於 [28442cc](https://github.com/mirror-tv/Tabris/pull/29/commits/28442ccd853b4a3acd779a20631b3c4edd805351) 修改，再麻煩幫忙看看有沒有缺漏，感謝！

2024-01-22 02:25 UTC, bibibobobi commented
我這邊沒有問題了，辛苦了🚀🥇🎉🎈

2024-01-22 02:27 UTC, bibibobobi approved these changes

2024-01-22 07:46 UTC, v61265 commented on packages/mirror-tv-next/components/shared/ui-post-card.tsx
> +  // 限制 brief 字數
和 PM 溝通後確定拿掉，已於 [f7ffd49](https://github.com/mirror-tv/Tabris/pull/29/commits/f7ffd49b9d8105d7d09ccf1d62e8ec91c95464de) 修改

2024-01-22 08:37 UTC, v61265 commented on packages/mirror-tv-next/components/shared/ui-post-card.tsx
> +              <span className="g-video-news-img-icon" />
video icon 確認需求後已於 [ba00dcb](https://github.com/mirror-tv/Tabris/pull/29/commits/ba00dcbbecfaebbdf233f9fdf0756e3339f1d92c) 修改

2024-01-22 08:49 UTC, erase2004 approved these changes
LGTM 👏

2024-01-22 10:02 UTC, merged