feat: add topic page
mirror-tv/Tabris pull request #56
Opened 2024-02-04 18:18 UTC by v61265

### 描述
- 新增 topic 頁面
- [PRD](https://paper.dropbox.com/doc/Mirror-TV-Topic-Listing-Page-topic--CItNjYwRRCrth2ZlYP~NHQFKAg-xuloP8WZb0AoSyqkhitwo)
- 主要參考設計稿和現有頁面。

2024-02-05 03:50 UTC, erase2004 requested changes
這 PR 應該還沒完成？另外，關於 type 相關的問題，可以在開發過程中，執行 `yarn lint` 來進行確認，這樣就不會推上去 build 後才出錯。
另外，專案的 husky 和 lint-staged 設定不完全，導致 git commit 時沒做應該有的檢查
ref: https://jenniesh.github.io/dev/NPM/husky-lint-staged/

2024-02-05 03:50 UTC, erase2004 commented on packages/mirror-tv-next/utils/api-data-handler.ts
> +import type { ApiData } from '~/types/data'
檔案不存在

2024-02-05 03:50 UTC, erase2004 commented on packages/mirror-tv-next/utils/api-data-handler.ts
> +function handleApiData(apiData: ApiData) {
沒有 export 出來被使用

2024-02-05 03:50 UTC, erase2004 commented on packages/mirror-tv-next/utils/image-handler.ts
> +  const { heroImage } = post
post 是 Post 和 Topic type 的 union，所以 heroImage 是 Post.heroImage 和 Topic.heroImage 的集合，
在存取 A type 有的 property 但 B type 沒有的 property 的情況下，需要額外一些操作，避免出現 `ts2339: Property does not exist on type` 的錯誤
ref: 
1. https://www.typescriptlang.org/docs/handbook/2/narrowing.html#the-in-operator-narrowing
2. https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

2024-02-05 03:50 UTC, erase2004 commented on packages/mirror-tv-next/graphql/query/topic.ts
> +  heroImage: {
這是一個比較根本性的問題，關聯的資料如果不存在的話，如果是一對一的資料，例如一篇 Post 只會有一個對應的 heroImage，則回傳的結果會是 `null`；但如果是一對多的情況下，例如一篇 Post 會有多個 Tag，則回傳的結果會是 `[]`。目前在關聯資料的定義上，都預設它會是存在的，當實際遇上資料不存在的情況時，就可能產生問題。

2024-02-05 03:50 UTC, erase2004 commented on packages/mirror-tv-next/components/topic/topics-list-manager.tsx
> +  const [page, setPage] = useState(1)
ESLint 會報錯

2024-02-05 10:53 UTC, v61265 commented on packages/mirror-tv-next/utils/api-data-handler.ts
> +import type { ApiData } from '~/types/data'
忘記清掉了，感謝提醒，已於 [1ea1cbb](https://github.com/mirror-tv/Tabris/pull/56/commits/1ea1cbb70af51d4927a7831df2dfcd753b7938d3) 移除

2024-02-05 10:54 UTC, v61265 commented on packages/mirror-tv-next/utils/api-data-handler.ts
> +function handleApiData(apiData: ApiData) {
一樣是忘記清掉的，感謝提醒，已於 [1ea1cbb](https://github.com/mirror-tv/Tabris/pull/56/commits/1ea1cbb70af51d4927a7831df2dfcd753b7938d3) 移除（現在邏輯寫在 component 內，有需要共用的話再考慮移出來）

2024-02-05 11:47 UTC, bibibobobi commented on packages/mirror-tv-next/app/topic/page.tsx
> +    const topicsResponse = await fetchTopics({
目前「看更多」按鈕點了沒有作用，看了 nuxt 網站跟 prd，這邊應該是直接有幾個 topics 就抓幾則，所以應該可以移除整個 `fetchTopics` server action， 直接用 apollo-client 在這邊 query 全部的 topics。

2024-02-05 12:27 UTC, bibibobobi commented on packages/mirror-tv-next/styles/components/topic/topics-list-manager.module.scss
> +.topics {
.topic 內建議加上 `padding-bottom: 6px;` 不然最後一列卡片的陰影都會消失。

<img width="1105" alt="Screen Shot 2024-02-05 at 8 26 13 PM" src="https://github.com/mirror-tv/Tabris/assets/66411169/26628709-36e4-4a13-9dfd-912a81f39640">

2024-02-05 13:25 UTC, bibibobobi commented
`topic` 頁 跟 `tag/[name] `的 metadata 都尚未設定，應該可以之後發另一個 pr 統一處理。

2024-02-05 14:22 UTC, v61265 commented on packages/mirror-tv-next/utils/image-handler.ts
> +  const { heroImage } = post
太好了終於找到解法 🥺
十分感謝！已於 [0369ff4](https://github.com/mirror-tv/Tabris/pull/56/commits/0369ff402773cb9cd31033e1ee413ec87a1235cd) 修改～

2024-02-05 14:36 UTC, v61265 commented on packages/mirror-tv-next/styles/components/topic/topics-list-manager.module.scss
> +.topics {
感謝提醒，已於 [d2533d1](https://github.com/mirror-tv/Tabris/pull/56/commits/d2533d12c1be9e81617f42517ab704047251c00e) 修改

2024-02-06 03:13 UTC, v61265 commented on packages/mirror-tv-next/app/topic/page.tsx
> +    const topicsResponse = await fetchTopics({
感謝提醒，本來想說下個 PR 再做 load more 功能，但忘了標記，不好意思還要你們提醒 ><
這頁面的 load more 需求是無限滾動，因此直接挪用週刊 3.0 的寫法，已於 [7c56e45](https://github.com/mirror-tv/Tabris/pull/56/commits/7c56e452cca4244355a25a72eb1ed66906b3974e) 更新，還要再麻煩幫忙看看了，感謝

2024-02-06 03:14 UTC, v61265 commented on packages/mirror-tv-next/components/topic/topics-list-manager.tsx
> +  const [page, setPage] = useState(1)
抱歉這部分確實是還沒完成又忘記標記，相關邏輯已於 [7c56e45](https://github.com/mirror-tv/Tabris/pull/56/commits/7c56e452cca4244355a25a72eb1ed66906b3974e) 更新，再麻煩幫忙看看了，感謝！

2024-02-06 07:13 UTC, v61265 commented on packages/mirror-tv-next/graphql/query/topic.ts
> +  heroImage: {
感謝說明，目前已於 [456b684](https://github.com/mirror-tv/Tabris/pull/56/commits/456b6843bc059efba8c34a2e829caf9e8a4ec7a5) 做調整，目前應該沒有漏掉的 👀

2024-02-06 10:02 UTC, erase2004 requested changes
1. husky 和 lint-staged 相關的設定先還原，這樣的設定還是有問題的
2. ListingPost、Show 和 Sponsor 的 type 增加 null 後，對應的 code 也需要增加相關的處理，例如原本 Sponsor.logo 在增加 null 後，Sponsor type 的資料在使用 logo 成員數值時，就可能需要調整為 Sponsor.logo?.xxx 之類

2024-02-06 10:02 UTC, erase2004 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +type Children = (renderList: any[]) => JSX.Element
這裡會有 `no-unused-vars` 的 ESLint 的錯誤，但根本原因是 ESLint 沒設定正確，可以暫時先用 ESLint comment 來處理
ESLint 與 TypeScript 相關設定:
https://typescript-eslint.io/getting-started/

2024-02-06 10:02 UTC, erase2004 commented on packages/mirror-tv-next/components/topic/topics-list-manager.tsx
> +              <img src="/images/loading.svg" alt="loading page" />
這應該用 `next/image` 來處理了
ref: https://nextjs.org/docs/pages/api-reference/components/image

2024-02-06 10:02 UTC, erase2004 commented on packages/mirror-tv-next/components/topic/topics-list-manager.tsx
> +            <div style={{ margin: '0 auto', width: '100vw' }}>
有 SCSS 方式來處理 CSS 後，現在又多了 inline CSS 的方式，這裡使用 inline CSS 的考量是？

2024-02-06 10:02 UTC, erase2004 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
1. 使用了不少 any，但其實可以用 Generic 的方法來解決，目前先給過
ref: https://www.typescriptlang.org/docs/handbook/2/generics.html
2. 變數命名產生誤會，`fetchCount` 應該調整為 `totalAmount`，`fetchPage` 應該調整為 `fetchedAmount`，在
```TypeScript
  const hasUnFetchedData = useMemo(
    () => !(renderCount >= dataList.length && fetchPage >= fetchCount),
    [dataList.length, renderCount, fetchPage, fetchCount]
  )
```
的處理中，fetchPage 和 fetchCount 做比較會有問題，如果 page 是指 pagination 的第幾頁，那 count 是資料的總數，第幾頁和資料總數是無法比較的，應該用別的變數紀錄目前抓了多少筆數。

2024-02-06 12:16 UTC, bibibobobi commented on packages/mirror-tv-next/components/topic/topics-list-manager.tsx
> +            <div style={{ margin: '0 auto', width: '100vw' }}>
這邊的 style 建議改用新增 className 的方式來做處理，也需要把 loaderContainer 中的 spinner 圖片置中，並給一個 default 高度，避免 footer layout shifting 的問題，目前 spinner 是出現在左邊，大小似乎也不太正確。
<img width="1239" alt="Screen Shot 2024-02-06 at 7 45 09 PM" src="https://github.com/mirror-tv/Tabris/assets/66411169/0834f673-a2ba-4296-a06c-86c9fb36c24c">

2024-02-06 12:26 UTC, bibibobobi commented
另外有發現一個比較大的問題是在所有 posts 都 render 完之後，又多跑了一次 loading spinner，但已經沒有東西 render了，所以等他消失，footer 就會閃動一下，目前還沒有仔細看是哪邊出了問題，可能明天有時間再一起檢查一下。
<img width="1212" alt="Screen Shot 2024-02-06 at 8 22 15 PM" src="https://github.com/mirror-tv/Tabris/assets/66411169/250ce0d4-cb80-4a9e-8403-aaa0a1730939">

2024-02-06 12:52 UTC, bibibobobi commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +      <div className={styles.test}>
`style.test `中的內容，是否在測試時 console.log 即可？這一整包目前雖然 `display : none`，但其實都還是會出現在 html 中，是 user 不需要知道的資訊。

2024-02-10 13:26 UTC, v61265 commented on packages/mirror-tv-next/components/topic/topics-list-manager.tsx
> +            <div style={{ margin: '0 auto', width: '100vw' }}>
偷懶被發現了 >< 
1.
本來想說到時候其他頁要使用的時候可以直接照搬，可以減少多餘的維護，但仔細想想如果到時候有這個需求的話應該乖乖把 loading 切成 component 搬出來。
這部分交給之後會用到這個的人決定好了，總之我先乖乖寫入 parent component 的 style 裡面。
更改於此：[3feb1fe](https://github.com/mirror-tv/Tabris/pull/56/commits/3feb1fe1fb16883c74fc59fcf1a0289fe43ff397)

2.
然後不好意思我漏掉了，想請教一下 `footer layout shifting` 具體會造成什麼樣的問題呢？感謝 orz（因為 loading 區有一塊空白會有點怪，如果是嚴重到會影響頁面效能或評分的問題，可能需要想想其他解法 🤔）

2024-02-10 13:26 UTC, v61265 commented on packages/mirror-tv-next/components/topic/topics-list-manager.tsx
> +              <img src="/images/loading.svg" alt="loading page" />
感謝提醒，已於 [3feb1fe](https://github.com/mirror-tv/Tabris/pull/56/commits/3feb1fe1fb16883c74fc59fcf1a0289fe43ff397) 更改～

2024-02-10 13:37 UTC, v61265 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +      <div className={styles.test}>
了解，確實應該改變一下寫法。
我目前想到兩個解法，一個是整段用 `{ isTest && <內容 />}` 包起來，這樣不用更改太多。
另一個就是將 console.log 這樣寫：
```
useEffect(() => {
  if (!isTest) return
  console.log('內容')
}, [isTest, 其他東西.....])
```
看起來雖然很乾淨，也會被 `isTest` 變數擋掉，但會有很多 dependecy，我的理解是只要有一個改變就會再被觸發一次，應該也會讓這頁的邏輯變複雜？還是其實還好？

2024-02-10 13:47 UTC, v61265 commented
> ListingPost、Show 和 Sponsor 的 type 增加 null 後，對應的 code 也需要增加相關的處理，例如原本 Sponsor.logo 在增加 null 後，Sponsor type 的資料在使用 logo 成員數值時，就可能需要調整為 Sponsor.logo?.xxx 之類

感謝提醒，已於 [c7801ed](https://github.com/mirror-tv/Tabris/pull/56/commits/c7801edcb4a230e3ed4cf0be9a97d0fdff2d1482) 修改～

2024-02-10 13:55 UTC, v61265 commented
> husky 和 lint-staged 相關的設定先還原，這樣的設定還是有問題的
了解，已於 [a89df94](https://github.com/mirror-tv/Tabris/pull/56/commits/a89df94c9f0fb6bcccc7090a9a0498d21fa727d1) 修改

2024-02-11 04:07 UTC, bibibobobi commented on packages/mirror-tv-next/components/topic/topics-list-manager.tsx
> +            <div style={{ margin: '0 auto', width: '100vw' }}>
後來發現 footer 會閃動的問題應該是下面這個，需要 debug：

> 另外有發現一個比較大的問題是在所有 posts 都 render 完之後，又多跑了一次 loading spinner，但已經沒有東西 render了，所以等他消失，footer 就會閃動一下，目前還沒有仔細看是哪邊出了問題，可能明天有時間再一起檢查一下

2024-02-11 04:16 UTC, bibibobobi commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +      <div className={styles.test}>
我是想說是否再開發完這個功能，確認沒問題之後，可以移除這段測試用訊息？

2024-02-11 12:40 UTC, v61265 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +      <div className={styles.test}>
我猜他還會在這裡的原因，有一部分是幫助之後的工程師 debug 使用 🤔

2024-02-11 12:50 UTC, v61265 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +type Children = (renderList: any[]) => JSX.Element
抱歉可能是我這邊的環境也沒設置好，所以無法重現問題。目前先改用參考資料方式設定 eslint ，想跟你確認一下是指這樣更改嗎？感謝：[3876f51](https://github.com/mirror-tv/Tabris/pull/56/commits/3876f51b8bff5e834b1fcd460c8196447c9140bd)

2024-02-11 12:50 UTC, v61265 commented on packages/mirror-tv-next/components/topic/topics-list-manager.tsx
> +            <div style={{ margin: '0 auto', width: '100vw' }}>
不用陪我加班啦 XDDDDDDDDDDDDD

2024-02-11 13:15 UTC, v61265 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
1. 已於 [542d44a](https://github.com/mirror-tv/Tabris/pull/56/commits/542d44a2a202b3b839d0de7fed072e75ca93dd16) 修改，再麻煩幫忙看看，感謝！

2024-02-11 13:39 UTC, v61265 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
2. 於 [fefe3ae](https://github.com/mirror-tv/Tabris/pull/56/commits/fefe3ae71a9e7214d1d719166d7a63aeada95ec8) 中調整，原本 bibo 反應的閃爍問題也得到解決了，感謝～

2024-02-11 13:39 UTC, v61265 commented on packages/mirror-tv-next/components/topic/topics-list-manager.tsx
> +            <div style={{ margin: '0 auto', width: '100vw' }}>
我這邊好像一開始就沒注意到閃爍問題抱歉，目前照 tsuki 的建議改了一版，等你上班再幫我看看還有沒有這個問題就好，感恩～
[fefe3ae](https://github.com/mirror-tv/Tabris/pull/56/commits/fefe3ae71a9e7214d1d719166d7a63aeada95ec8)

2024-02-11 13:40 UTC, v61265 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +      <div className={styles.test}>
先在 [fefe3ae](https://github.com/mirror-tv/Tabris/pull/56/commits/fefe3ae71a9e7214d1d719166d7a63aeada95ec8) 裡藏起來 XD

2024-02-15 04:31 UTC, bibibobobi commented on packages/mirror-tv-next/components/topic/topics-list-manager.tsx
> +            <div style={{ margin: '0 auto', width: '100vw' }}>
沒有問題了，辛苦了～

2024-02-15 04:31 UTC, bibibobobi commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +      <div className={styles.test}>
真是聰明的方法，讚讚

2024-02-15 06:26 UTC, bibibobobi commented
我這邊沒有問題了 😎🧨🎊🧧

2024-02-15 06:26 UTC, bibibobobi approved these changes

2024-02-19 05:10 UTC, erase2004 requested changes
ESLint 相關的 package 是裝對了，但設定還是有問題，需要留意以下幾點：
1. 這是 Next.js 為主的 git repo
2. 這是以 monorepo 方式管理
因此，直接把 ESLint 設定直接移到 packges 下，則用 monorepo 管理的優點會消失，
再來，ESLint 中沒有 Next.js 相關的 rule，
結論，ESLint 設定的修改，同時讓這兩項需要注意的點都出問題了，
合理且通用的設定應該如下：
```Json
{
  "extends": [
    "next/core-web-vitals",
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended"
  ],
  "plugins": ["@typescript-eslint", "prettier"],
  "parserOptions": {
    "ecmaVersion": 2021,
    "sourceType": "module"
  },
  "rules": {
    "prettier/prettier": "error",
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": "error"
  }
}
```
順道一題，
ESLint 相關的問題，可以在 pacakage 下執行 `yarn lint` 做驗證
![Snipaste_2024-02-19_13-09-18](https://github.com/mirror-tv/Tabris/assets/1367757/4d6504be-ae4f-417c-9550-283dd1c083a6)

2024-02-19 05:10 UTC, erase2004 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +        fetchedPage >= Math.ceil(totalCount / pageSize)
既然 `totalCount` 和 `pageSize` 的值再被 assign 之後都是固定的，那 `Math.ceil(totalCount / pageSize)` 得到的結果也會是固定的，所以應該用一個變數儲存這計算結果，而不是讓使用到的地方都重新呼叫一次

2024-02-19 05:10 UTC, erase2004 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +        <div className={styles.test}>
這一區塊的除錯完全可以用 React Dev Tool 來處理
![Snipaste_2024-02-19_12-49-33](https://github.com/mirror-tv/Tabris/assets/1367757/db6d62a8-18dd-445a-94a2-bc101118cbaa)

2024-02-19 05:50 UTC, v61265 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +        fetchedPage >= Math.ceil(totalCount / pageSize)
已於 [60bc5da](https://github.com/mirror-tv/Tabris/pull/56/commits/60bc5daed249f7f04e1da7067726212c54fbc727) 修改
另外確認一下，因為此處的 dependecy 都是 props 而非 state，我的理解是除非 props 有改變（這樣該 component 就會重新 render）該值基本上不會更動，因此就沒有用 useMemo 包起來 >> 這個理解是對的嗎？

2024-02-19 07:26 UTC, v61265 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +        <div className={styles.test}>
好ㄅ大家都是成熟的工程師了，我先於 [60bc5da](https://github.com/mirror-tv/Tabris/pull/56/commits/60bc5daed249f7f04e1da7067726212c54fbc727) 移除

2024-02-19 07:32 UTC, v61265 commented
> ESLint 相關的 package 是裝對了，但設定還是有問題，需要留意以下幾點：
> 
> 1. 這是 Next.js 為主的 git repo
> 2. 這是以 monorepo 方式管理
>    因此，直接把 ESLint 設定直接移到 packges 下，則用 monorepo 管理的優點會消失，
>    再來，ESLint 中沒有 Next.js 相關的 rule，
>    結論，ESLint 設定的修改，同時讓這兩項需要注意的點都出問題了，
>    合理且通用的設定應該如下：

已於 [e58e227](https://github.com/mirror-tv/Tabris/pull/56/commits/e58e22768b112ddfb3861d14315a54474b0afa47) 修改，再麻煩看看，感謝 ><

2024-02-19 07:51 UTC, erase2004 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +        fetchedPage >= Math.ceil(totalCount / pageSize)
可以不加此變數到 deps array

2024-02-19 07:53 UTC, erase2004 requested changes

2024-02-19 07:53 UTC, erase2004 commented on packages/mirror-tv-next/tsconfig.json
> +    "strict": false,
不是很懂，這裡是關於 ESLint 設定的回覆，但實際調整卻是對 tsconfig
https://github.com/mirror-tv/Tabris/pull/56#issuecomment-1951855351

2024-02-19 08:40 UTC, v61265 commented on packages/mirror-tv-next/tsconfig.json
> +    "strict": false,
抱歉抱歉，我頭暈了，已於 [d57dee8](https://github.com/mirror-tv/Tabris/pull/56/commits/d57dee85f18040cbfcd63a5f23901d0905e6a356) 復原，並且於 [72eed02](https://github.com/mirror-tv/Tabris/pull/56/commits/72eed02bcb2ec94bbe5dd1a680deb8c441ce7cbe) 調整成 json  格式，不確定是不是你原本的意思？

2024-02-19 08:43 UTC, v61265 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +        fetchedPage >= Math.ceil(totalCount / pageSize)
剛剛被 eslint 提醒還是加上去了，詳見：[dd3e12e](https://github.com/mirror-tv/Tabris/pull/56/commits/dd3e12eed4a4fece02a83838a5f5d39d0359bb9e)

2024-02-19 09:19 UTC, erase2004 approved these changes
ACK

2024-02-19 09:19 UTC, erase2004 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +  const totalPage = useMemo(
這個用上 useMemo 不太有意義
https://react.dev/reference/react/useMemo

2024-02-19 15:45 UTC, v61265 commented on packages/mirror-tv-next/components/shared/infinite-scroll-list.tsx
> +  const totalPage = useMemo(
好那我不要管 warning 了，已於 [130482d](https://github.com/mirror-tv/Tabris/pull/56/commits/130482d6e8e1213b549e3a79cdb323bf9e7cbe03) 修改。

2024-02-19 15:46 UTC, merged