feat(tv): add category page
mirror-tv/Tabris pull request #68
Opened 2024-02-22 09:12 UTC by v61265

### 描述
- 新增 category 頁面

2024-02-23 04:30 UTC, erase2004 requested changes
先送個 PR 把 husky 和 lint-staged 的問題給修正吧，
不然這個 PR 又出現 ESLint error，
照理來說，在 git commit 前，就該處理好 ESLint error 相關的問題了

2024-02-23 06:24 UTC, v61265 commented
okok 可以先處理這個：https://github.com/mirror-tv/Tabris/pull/70

2024-02-23 06:29 UTC, v61265 commented
另外先用 `yarn lint` 抓到一個問題，先於 [4c9d219](https://github.com/mirror-tv/Tabris/pull/68/commits/4c9d2199a7ecb283413e07e228d9caabf23b69cd) 解決。

2024-02-23 09:29 UTC, v61265 commented
### 調整
- 確定 pre-commit husky
- 使用 yarn lint 修改錯誤提示

2024-02-24 04:54 UTC, bibibobobi commented
Tablet 尺寸 側欄應該有 border，目前的沒有。
<img width="300" alt="Screen Shot 2024-02-24 at 12 51 37 PM" src="https://github.com/mirror-tv/Tabris/assets/66411169/9704aaf5-cdef-42b0-976c-ba9aabc66281"><img width="280" alt="Screen Shot 2024-02-24 at 12 51 18 PM" src="https://github.com/mirror-tv/Tabris/assets/66411169/9239aab6-cc46-401e-a872-ff0301232585">

2024-02-24 05:08 UTC, bibibobobi commented on packages/mirror-tv-next/graphql/query/categories.ts
這個檔案請先幫我保留，會用到裡面的 types

2024-02-24 05:15 UTC, bibibobobi commented on packages/mirror-tv-next/utils/common.ts
> +function getGcsJsonUrl(fileName: string): string {
JSON url 目前統一管理在 `environment-variables.ts` ，如果要用 SITE_URL 取代部分網址，應該也可以從那邊。

2024-02-24 05:26 UTC, bibibobobi commented on packages/mirror-tv-next/app/category/[slug]/page.tsx
> +    <section className={styles.category}>
電視 Nuxt 原先的 HTML 結構有點問題，我覺得可以趁改版修正過來，像這邊 section 不應該包覆 main，如果要符合Semantic HTML 的結構，main 應該是僅次於 body之外唯一的 element，Specifies the main content of a document ，而 section 通常用來區分段落，一個頁面可有多個 section，應該是像下面這張圖：
<img width="582" alt="Screen Shot 2024-02-24 at 1 22 18 PM" src="https://github.com/mirror-tv/Tabris/assets/66411169/d684c16f-0791-4b33-a8da-5cfaf8fa5fb6">
所以這邊應該需要把 section 跟 main tag 交換。

2024-02-24 06:27 UTC, bibibobobi commented on packages/mirror-tv-next/app/category/[slug]/page.tsx
> +  const fetchPopularPosts = () => axios.get(getGcsJsonUrl('/popularlist'))
這邊建議直接使用 fetch 就好，不要用 axios，Nextjs 有針對原生的 fetch() API 做延伸應用，也針對 app router 有 cache options 可以選擇，舉例來說，像這樣：
```
 const res = await fetch(SCHEDULE_JSON_URL, {
      next: { revalidate: GLOBAL_CACHE_SETTING },
    })
```
可以參考[這邊的寫法](https://github.com/mirror-tv/Tabris/blob/a9311a4bc4c91f755be5058b2f0b524581dc3d2d/packages/mirror-tv-next/app/schedule/page.tsx#L29) ，[參考文件](https://nextjs.org/docs/app/api-reference/functions/fetch)

2024-02-24 06:45 UTC, bibibobobi commented on packages/mirror-tv-next/app/category/[slug]/page.tsx
> +      throw new Error('Error occurs while fetching data.')
這邊應該 return [] 就好，如果 throw new Error，任何一個 list 沒有拿到資料，就會整個壞掉。

2024-02-24 06:51 UTC, bibibobobi commented on packages/mirror-tv-next/components/shared/ui-heading-bordered.tsx
> +export const revalidate = GLOBAL_CACHE_SETTING
component 不需要 revalidate setting

2024-02-24 06:58 UTC, bibibobobi commented on packages/mirror-tv-next/styles/pages/category.module.scss
> +  min-height: calc(100vh - 50px); // header height
建議 100vh 可以都改成 100dvh
值得一看影片： [Use 100dvh, not 100vh (CSS Units)](https://www.youtube.com/watch?v=O16af0iRs44)

2024-02-24 07:54 UTC, bibibobobi commented on packages/mirror-tv-next/styles/components/shared/ui-list-posts-aside.module.scss
> +.bordered {
Tablet 尺寸 側欄應該有 border 和 gap，目前的沒有。
<img width="300" alt="Screen Shot 2024-02-24 at 12 51 37 PM" src="https://github.com/mirror-tv/Tabris/assets/66411169/9704aaf5-cdef-42b0-976c-ba9aabc66281"><img width="280" alt="Screen Shot 2024-02-24 at 12 51 18 PM" src="https://github.com/mirror-tv/Tabris/assets/66411169/9239aab6-cc46-401e-a872-ff0301232585">

2024-02-24 08:20 UTC, bibibobobi commented
**疑問**：有一個疑惑的地方是，目前 nuxt 個分類的 feature article，好像有抓勾選置頂的 post，但剛剛去看 [PRD ](https://paper.dropbox.com/doc/Mirror-TV-Listing-Page-category--CKFEdAl9iuwQ7TDdYxew0PCeAg-LBlykMIiJ3eQfqvLtQ1iq) 並沒有提到這個需求 🤔
<img width="455" alt="Screen Shot 2024-02-24 at 4 18 59 PM" src="https://github.com/mirror-tv/Tabris/assets/66411169/e5a1ae34-f6ee-4ec2-9032-dfca19011f2a">

2024-02-24 08:29 UTC, bibibobobi commented on packages/mirror-tv-next/app/category/[slug]/page.tsx
> +            <UiFeaturePost post={categoryPosts[0]} />
**疑問**：有一個疑惑的地方是，目前 nuxt 個分類的 feature article，好像有抓勾選置頂的 post，但剛剛去看 [PRD ](https://paper.dropbox.com/doc/Mirror-TV-Listing-Page-category--CKFEdAl9iuwQ7TDdYxew0PCeAg-LBlykMIiJ3eQfqvLtQ1iq) 並沒有提到這個需求 🤔
<img width="455" alt="Screen Shot 2024-02-24 at 4 18 59 PM" src="https://github.com/mirror-tv/Tabris/assets/66411169/e5a1ae34-f6ee-4ec2-9032-dfca19011f2a">

2024-02-24 10:57 UTC, bibibobobi commented
因為現在 cetegory 頁面其實都共用同一個 Aside Conponent，建議可以在 `app/category/[slug]` 的資料夾裡新增一個 `layout.tsx`，在裡面render 一個 MainAside component，從 MainAside component fetch 熱門新聞跟最新新聞，這樣就不用每個 cetegory 都重新抓一次資料，具體做法可以參考 [MainHeader](https://github.com/mirror-tv/Tabris/blob/dev/packages/mirror-tv-next/components/layout/header/main-header.tsx) 和 [root layout](https://github.com/mirror-tv/Tabris/blob/dev/packages/mirror-tv-next/app/layout.tsx)

2024-02-25 11:57 UTC, erase2004 requested changes

2024-02-25 11:57 UTC, erase2004 commented on packages/mirror-tv-next/app/category/[slug]/page.tsx
> +      'Error occurs while fetching data for category for category page'
Should be `Error occurs while fetching category data in category page` ?

2024-02-25 11:57 UTC, erase2004 commented on packages/mirror-tv-next/utils/common.ts
> +    ? `https://dev.mnews.tw/json/${fileName}.json`
`/json/` 這個路徑看起來是在 load balancer 上做設定，我好奇這個設計的存在原因，是否能和週刊一樣，都改用另外的 domain 來處理就好了。

2024-02-25 11:57 UTC, erase2004 commented on packages/mirror-tv-next/app/category/[slug]/page.tsx
> +  const handledResponses = responses.map((response) => {
Ln. 116 ~ Ln. 183 的結構可以調整為：
增加一個 function，input 1 是 promise result，input 2 是針對 input 1 這個 promise result 的處理 function，輸出結果是 input 2 的執行結果，用 type 來表示就是
```TypeScript
type PromiseResultHandler<T extends Record<string, any>, U extends PromiseSettledResult<T>, V> = (result: U, func: (value: T | undefined) => U) => U
```
然後 `categoryPostsData`、`latestPostsData` 和 `popularPostsData`  用
```TypeScript
const resultN = PromiseResultHandler(response[n], funcN())
```
的型式取代
這麼做得好處是 `categoryPostsData`、`latestPostsData` 和 `popularPostsData` 不再是 any，
在型別處理上更加完整

2024-02-25 11:57 UTC, erase2004 commented on packages/mirror-tv-next/components/category/action.tsx
> +    throw new Error('Error occurs while fetching data.')
應該 throw 已經包好的 `annotatingError`，而不是再創建一個新的 error 來 throw

2024-02-26 03:45 UTC, v61265 commented on packages/mirror-tv-next/styles/components/shared/ui-list-posts-aside.module.scss
> +.bordered {
我也有點困惑這個部分，但我看現在舊版 [這個頁面](https://www.mnews.tw/category/int) 的平板是沒有框框的，感覺要一起和需求方確定 🤔

2024-02-26 04:28 UTC, v61265 commented on packages/mirror-tv-next/components/category/action.tsx
> +    throw new Error('Error occurs while fetching data.')
ok，已於 [71878ac](https://github.com/mirror-tv/Tabris/pull/68/commits/71878ac903c01770aa16f4bbedb3b327a01dedf2) 修改。

2024-02-26 04:48 UTC, v61265 commented on packages/mirror-tv-next/components/category/action.tsx
> +    throw new Error('Error occurs while fetching data.')
感謝提醒，已於 [5f250f7](https://github.com/mirror-tv/Tabris/pull/68/commits/5f250f71a456782f56ab3954b7ba390b717bf5be) 修改

2024-02-26 04:48 UTC, v61265 commented on packages/mirror-tv-next/app/category/[slug]/page.tsx
> +      'Error occurs while fetching data for category for category page'
感謝提醒，已於 [5f250f7](https://github.com/mirror-tv/Tabris/pull/68/commits/5f250f71a456782f56ab3954b7ba390b717bf5be) 修改

2024-02-26 04:48 UTC, v61265 commented on packages/mirror-tv-next/app/category/[slug]/page.tsx
> +      throw new Error('Error occurs while fetching data.')
感謝提醒，已於 [5f250f7](https://github.com/mirror-tv/Tabris/pull/68/commits/5f250f71a456782f56ab3954b7ba390b717bf5be) 修改

2024-02-26 06:24 UTC, v61265 commented on packages/mirror-tv-next/components/shared/ui-heading-bordered.tsx
> +export const revalidate = GLOBAL_CACHE_SETTING
感謝提醒，已於 [62f7fb2](https://github.com/mirror-tv/Tabris/pull/68/commits/62f7fb2fca521d1de437a998c6c9fd822eeb2b09) 修改

2024-02-26 07:46 UTC, v61265 commented on packages/mirror-tv-next/styles/components/shared/ui-list-posts-aside.module.scss
> +.bordered {
結果是之前被誤改，已於 [c08b236](https://github.com/mirror-tv/Tabris/pull/68/commits/c08b2360ddcab6df7a319bc85f84c6bc5b2653b6) 修改 XD

2024-02-26 08:01 UTC, v61265 commented on packages/mirror-tv-next/styles/pages/category.module.scss
> +  min-height: calc(100vh - 50px); // header height
感謝補充，已於 [c08b236](https://github.com/mirror-tv/Tabris/pull/68/commits/c08b2360ddcab6df7a319bc85f84c6bc5b2653b6) 修改

2024-02-26 08:14 UTC, v61265 commented on packages/mirror-tv-next/utils/common.ts
> +function getGcsJsonUrl(fileName: string): string {
感謝說明（和陪我鬼打牆），已於 [8d3e8e2](https://github.com/mirror-tv/Tabris/pull/68/commits/8d3e8e24d3f98c10f9fdb9b67f8aa0ec8bbd73e7) 修改～

2024-02-26 08:16 UTC, v61265 commented on packages/mirror-tv-next/utils/common.ts
> +    ? `https://dev.mnews.tw/json/${fileName}.json`
我目前在 [8d3e8e2](https://github.com/mirror-tv/Tabris/pull/68/commits/8d3e8e24d3f98c10f9fdb9b67f8aa0ec8bbd73e7) 先更改位置了，如果有新的 endpoint 到時候可以一併給我修改，感謝！

2024-02-27 04:03 UTC, v61265 commented on packages/mirror-tv-next/app/category/[slug]/page.tsx
> +  const fetchPopularPosts = () => axios.get(getGcsJsonUrl('/popularlist'))
感謝提醒，已於 [d203e78](https://github.com/mirror-tv/Tabris/pull/68/commits/d203e78607d33b575382583d533aa93bb36b8f1b) 修改

2024-02-27 04:03 UTC, v61265 commented on packages/mirror-tv-next/app/category/[slug]/page.tsx
> +    <section className={styles.category}>
感謝提醒，已於 [d203e78](https://github.com/mirror-tv/Tabris/pull/68/commits/d203e78607d33b575382583d533aa93bb36b8f1b) 修改

2024-02-27 04:04 UTC, v61265 commented on packages/mirror-tv-next/app/category/[slug]/page.tsx
> +  const handledResponses = responses.map((response) => {
感謝說明，已於 [d203e78](https://github.com/mirror-tv/Tabris/pull/68/commits/d203e78607d33b575382583d533aa93bb36b8f1b) 試試看一個版本，但不是很確定是否正確？再麻煩有空幫忙看看，感謝！

2024-02-27 04:04 UTC, v61265 commented
> 因為現在 cetegory 頁面其實都共用同一個 Aside Conponent，建議可以在 `app/category/[slug]` 的資料夾裡新增一個 `layout.tsx`，在裡面render 一個 MainAside component，從 MainAside component fetch 熱門新聞跟最新新聞，這樣就不用每個 cetegory 都重新抓一次資料，具體做法可以參考 [MainHeader](https://github.com/mirror-tv/Tabris/blob/dev/packages/mirror-tv-next/components/layout/header/main-header.tsx) 和 [root layout](https://github.com/mirror-tv/Tabris/blob/dev/packages/mirror-tv-next/app/layout.tsx)

感謝說明，已於 [d203e78](https://github.com/mirror-tv/Tabris/pull/68/commits/d203e78607d33b575382583d533aa93bb36b8f1b) 修改

2024-02-27 09:04 UTC, v61265 commented on packages/mirror-tv-next/app/category/[slug]/page.tsx
> +            <UiFeaturePost post={categoryPosts[0]} />
好像是這個 json 檔都要優先顯示，但不確定原理：https://dev.mnews.tw/json/featured_categories_post.json
目前已於 slask 提出討論，等待需求方回應。
如果卡太久會 conflict 的話，建議之後另外發 PR 處理？

2024-02-29 03:20 UTC, v61265 commented
## 等該 commit 結束之後的 todo
以下因為 prd 上本來沒有，但其實也是需求，因此等該 commit 結束後再額外發 pr 處理。
- [ ] sale posts 插入
- [ ] 置頂文章選用

2024-02-29 03:42 UTC, erase2004 requested changes

2024-02-29 03:42 UTC, erase2004 commented on packages/mirror-tv-next/app/category/[slug]/page.tsx
> +      'Error occurs while fetching data for category for category page'
force push 後修正被蓋掉了

2024-02-29 03:42 UTC, erase2004 commented on packages/mirror-tv-next/app/category/[slug]/page.tsx
> +      'Error occurs while fetching data for category for category page'
另外 Ln. 94 也有相同問題

2024-02-29 03:42 UTC, erase2004 commented on packages/mirror-tv-next/components/category/action.tsx
> +      'Error occurs while fetching data for posts for tag page'
tag page?

2024-02-29 03:42 UTC, erase2004 commented on packages/mirror-tv-next/components/category/action.tsx
> +        first: page === 0 ? pageSize + 1 : pageSize,
請問在 page #0 的情況下，需要多抓 1 筆的原因是？

2024-02-29 03:42 UTC, erase2004 commented on packages/mirror-tv-next/app/category/[slug]/layout.tsx
> +      console.log(
既然 `severity: 'ERROR'` 了，那這裡應該用的是 `console.error` 而不是 `console.log`

2024-02-29 03:42 UTC, erase2004 commented on packages/mirror-tv-next/utils/index.ts
>  export {
formatArticleCard 的匯出消失了

2024-02-29 03:42 UTC, erase2004 commented on packages/mirror-tv-next/app/category/[slug]/layout.tsx
修改方向上大致正確，但還是有些問題（包含 ESLint），patch 套用後，建議理解調整內容，有問題可以再提問

[layout.tsx.patch](https://github.com/mirror-tv/Tabris/files/14442516/layout.tsx.patch)

patch 使用教學
https://gist.github.com/nepsilon/22bc62a23f785716705c

2024-02-29 04:58 UTC, bibibobobi commented on packages/mirror-tv-next/app/category/[slug]/layout.tsx
> +      <aside className={styles.aside}>
我會比較傾向不要在 layout fetch 資料，這邊可以 import 一個 `mainAside` component，在該 component fetch 熱門新聞和最新新聞（參考 `mainHeader` component 的做法），讓 layout 回歸到只 render 共用的 component 跟 dynamic metadata。之後如果需要個別區塊的錯誤處理，也可以把 error.js 放在該 component. [這邊有一些討論也許可以看一下](https://www.reddit.com/r/nextjs/comments/1axhp0a/is_it_bad_to_fetch_data_in_page_or_layout/)

2024-02-29 05:15 UTC, bibibobobi commented on packages/mirror-tv-next/styles/pages/category-layout.module.scss
> +  display: flex;
這邊要加 `flex-direction: column;`
<img width="195" alt="Screen Shot 2024-02-29 at 1 00 03 PM" src="https://github.com/mirror-tv/Tabris/assets/66411169/0e95c042-4fb6-4540-abb9-79f1cbd1bb06">

2024-02-29 05:16 UTC, bibibobobi commented on packages/mirror-tv-next/styles/pages/category-layout.module.scss
> +    width: 688px;
`flex-direction: row;`

2024-02-29 05:16 UTC, v61265 commented on packages/mirror-tv-next/components/category/action.tsx
> +        first: page === 0 ? pageSize + 1 : pageSize,
因為第一頁會需要置頂文章（最上面那塊），所以是需要多抓一篇。

2024-02-29 06:32 UTC, v61265 commented on packages/mirror-tv-next/components/category/action.tsx
> +      'Error occurs while fetching data for posts for tag page'
不好意思還需要一直提醒，已於 [33fb382](https://github.com/mirror-tv/Tabris/pull/68/commits/33fb3828a3f4cdb918472719031e28d536b36a4f) 修改

2024-02-29 06:32 UTC, v61265 commented on packages/mirror-tv-next/app/category/[slug]/layout.tsx
> +      console.log(
感謝提醒，已於 [33fb382](https://github.com/mirror-tv/Tabris/pull/68/commits/33fb3828a3f4cdb918472719031e28d536b36a4f) 修改。

2024-02-29 06:33 UTC, v61265 commented on packages/mirror-tv-next/utils/index.ts
>  export {
感謝提醒，已於 [33fb382](https://github.com/mirror-tv/Tabris/pull/68/commits/33fb3828a3f4cdb918472719031e28d536b36a4f) 修改

2024-02-29 09:21 UTC, v61265 commented on packages/mirror-tv-next/app/category/[slug]/layout.tsx
感謝說明，已於 [e857d7f](https://github.com/mirror-tv/Tabris/pull/68/commits/e857d7f7e1cbcb403d917304d95dcb43baa2d132) 調整。
其中有看到 `TODO: post in json doesn't have 'style' attribute` 的部分，因為該欄位主要會影響的是某些地方的 UI，目前熱門文章這裡好像沒有對應樣式（剛好用不到 style 欄位），因此我先手動讓所有 style 都是 article。

2024-02-29 09:50 UTC, v61265 commented on packages/mirror-tv-next/app/category/[slug]/layout.tsx
> +      <aside className={styles.aside}>
感謝詳細說明，已於 [ddd99d9](https://github.com/mirror-tv/Tabris/pull/68/commits/ddd99d925175eeeb5d8078112c09890596e18f78) 調整。

2024-02-29 09:50 UTC, v61265 commented on packages/mirror-tv-next/styles/pages/category-layout.module.scss
> +  display: flex;
哇大漏掉，感謝提醒，已於 [ddd99d9](https://github.com/mirror-tv/Tabris/pull/68/commits/ddd99d925175eeeb5d8078112c09890596e18f78) 調整。

2024-02-29 09:51 UTC, v61265 commented on packages/mirror-tv-next/styles/pages/category-layout.module.scss
> +    width: 688px;
感謝提醒，已於 [ddd99d9](https://github.com/mirror-tv/Tabris/pull/68/commits/ddd99d925175eeeb5d8078112c09890596e18f78) 修改

2024-02-29 10:04 UTC, bibibobobi commented
我這邊沒有問題了，辛苦了🎉🥇🚀👍

2024-02-29 10:05 UTC, bibibobobi approved these changes

2024-02-29 10:26 UTC, erase2004 requested changes
Almost

2024-02-29 10:26 UTC, erase2004 commented on packages/mirror-tv-next/components/category/action.tsx
> +    throw new Error(annotatingError)
不用再用 Error 包起來

2024-02-29 10:26 UTC, erase2004 commented on packages/mirror-tv-next/components/category/action.tsx
> +        first: page === 0 ? pageSize + 1 : pageSize,
註解標示一下有這部份的需求

2024-02-29 10:26 UTC, erase2004 commented on packages/mirror-tv-next/components/category/layout/aside.tsx
> +      // TODO: post in json doesn't have 'style' attribute
移除 `TODO: `，保留後面的文字，除非有要再進一步處理

2024-02-29 10:46 UTC, v61265 commented on packages/mirror-tv-next/components/category/action.tsx
> +    throw new Error(annotatingError)
已於 [2998e3a](https://github.com/mirror-tv/Tabris/pull/68/commits/2998e3a32491126d0f768c38925a3cfd119de513) 修改

2024-02-29 10:46 UTC, v61265 commented on packages/mirror-tv-next/components/category/layout/aside.tsx
> +      // TODO: post in json doesn't have 'style' attribute
已於 [2998e3a](https://github.com/mirror-tv/Tabris/pull/68/commits/2998e3a32491126d0f768c38925a3cfd119de513) 修改

2024-02-29 15:28 UTC, erase2004 approved these changes
Pass 👏

2024-03-01 03:30 UTC, merged