feat(tv/video): add page of video category
mirror-tv/Tabris pull request #79
Opened 2024-03-13 15:10 UTC by v61265

### 描述
- 新增影音頁面（不含側欄）

### 問題
- 在 fetch more data 時會無法滑動。

2024-03-15 08:52 UTC, erase2004 requested changes

2024-03-15 08:52 UTC, erase2004 commented on packages/mirror-tv-next/components/category/video/action.tsx
> +      'Error occurs while fetching category posts data in category page'
error message 應該調整？

2024-03-15 08:52 UTC, erase2004 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +export default async function CategoryPage() {
應該換個名字，和其他 CategoryPage 區隔開？

2024-03-15 08:52 UTC, erase2004 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +    id: string
建議把這一塊的定義抽出來表示

2024-03-15 08:52 UTC, erase2004 commented on packages/mirror-tv-next/utils/common.ts
> +      'Error occurs while fetching category data in category page'
錯誤訊息可能要藉由傳入的參數來客製化

2024-03-15 08:52 UTC, erase2004 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +    | never[] = []
`never[]` 多餘的，而且使用上不正確

2024-03-15 08:52 UTC, erase2004 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +              categoryName={getCategoryNameBySlug(list.categorySlug)}
我會建議把 `getCategoryNameBySlug` 的計算結果放到 categoryPosts 中的每個項目，讓 categoryPosts 的項目都有 categoryName 的屬性

2024-03-15 08:52 UTC, erase2004 commented on packages/mirror-tv-next/components/category/video/video-posts-list.tsx
> +      if (width >= tabletWidthThreshold) {
desktop 縮到 tablet，顯示的 slides 不會變成 2 個

2024-03-15 08:52 UTC, erase2004 commented on packages/mirror-tv-next/components/category/video/video-posts-list.tsx
> +    const handleResize = () => {
handelResize 定義可以不用放到 useEffect 中

2024-03-15 08:52 UTC, erase2004 commented on packages/mirror-tv-next/components/category/video/video-posts-list.tsx
> +    const handleResize = () => {
page 應該也需要在 resize 過程中進行變動
舉例：在資料為 [1,2,3,4,5,6,7,8] 的情況下，
目前 slidesPerView 為 3，則 page 1 有 [4,5,6]；
但在 slidesPerView 為 2 的情況下， page 1 有 [3,4]

2024-03-15 08:52 UTC, erase2004 commented on packages/mirror-tv-next/components/category/video/video-posts-list.tsx
> +          {placeholder.map((item, index) => {
不清楚 placeholder 的用途

2024-03-18 05:50 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/video-posts-list.tsx
> +          {placeholder.map((item, index) => {
如果不這樣寫的話，套件最後一次好像就不會顯示空白的區塊

2024-03-18 08:12 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/action.tsx
> +      'Error occurs while fetching category posts data in category page'
感謝提醒，已於 [880cf05](https://github.com/mirror-tv/Tabris/pull/79/commits/880cf059cc44c0dfbd4328ddd5bfe200a752997a) 修改。

2024-03-18 08:12 UTC, v61265 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +export default async function CategoryPage() {
感謝提醒，已於 [880cf05](https://github.com/mirror-tv/Tabris/pull/79/commits/880cf059cc44c0dfbd4328ddd5bfe200a752997a) 修改。

2024-03-18 08:13 UTC, v61265 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +    id: string
感謝提醒，已於 [880cf05](https://github.com/mirror-tv/Tabris/pull/79/commits/880cf059cc44c0dfbd4328ddd5bfe200a752997a) 修改。

2024-03-18 08:13 UTC, v61265 commented on packages/mirror-tv-next/utils/common.ts
> +      'Error occurs while fetching category data in category page'
ok，已於 [880cf05](https://github.com/mirror-tv/Tabris/pull/79/commits/880cf059cc44c0dfbd4328ddd5bfe200a752997a) 修改

2024-03-18 08:13 UTC, v61265 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +    | never[] = []
感謝提醒，已於 [880cf05](https://github.com/mirror-tv/Tabris/pull/79/commits/880cf059cc44c0dfbd4328ddd5bfe200a752997a) 修改

2024-03-18 08:14 UTC, v61265 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +              categoryName={getCategoryNameBySlug(list.categorySlug)}
感謝說明，已於 [880cf05](https://github.com/mirror-tv/Tabris/pull/79/commits/880cf059cc44c0dfbd4328ddd5bfe200a752997a) 修改

2024-03-20 04:33 UTC, bibibobobi commented
剛剛去看 [spec](https://paper.dropbox.com/doc/Mirror-TV-Video-Page-categoryvideo--CLpRk0twrgMc_8dfbN3Hy915Ag-jdj1rkmTLVA0w7C3O5dmZ) 發現除了分類，還要抓熱門影音，這隻[JSON](https://storage.googleapis.com/static-mnews-tw-prod/json/popular-videonews-list.json)
<img width="841" alt="Screen Shot 2024-03-20 at 12 32 55 PM" src="https://github.com/mirror-tv/Tabris/assets/66411169/37a67f76-e916-4088-a364-eb5d8bf10150">

2024-03-20 10:06 UTC, bibibobobi commented on packages/mirror-tv-next/app/category/video/page.tsx
> +            categoryName="熱門新聞"
正式機這個 categoryName 似乎是叫「熱門影音」，和設計稿不太一樣

2024-03-20 12:32 UTC, bibibobobi commented on packages/mirror-tv-next/components/category/video/video-posts-list.tsx
> +    const handleResize = () => {
這邊應該改這樣，小於 768 尺寸應該是兩欄，大於 768 是三欄，1200 這個斷點不需要。
```
const handleResize = () => {
      const width = window.innerWidth
      const tabletWidthThreshold = 768

      if (width >= tabletWidthThreshold) {
        setGapPx(24)
        setSlidesPerView(3)
      } else if (width < tabletWidthThreshold) {
        setGapPx(20)
        setSlidesPerView(2)
      }
    }
```

2024-03-20 13:35 UTC, bibibobobi commented on packages/mirror-tv-next/components/category/video/video-posts-list.tsx
> +    const placeholderCount = 3 - (postsList.length % 3)
SlidesPerView 是兩欄的時候，placeholderCount 的計算也要改，我們是不是在參加數學學測ＸＤ

2024-03-20 15:31 UTC, bibibobobi commented on packages/mirror-tv-next/styles/components/category/video/video-post-card.module.scss
> +  height: 100%;
video post card 的 wrapper 要給他一個高度，應該是168px，不然會有 layout shifting 的問題，然後 spinner 的大小會需要調整，或是拿掉。

https://github.com/mirror-tv/Tabris/assets/66411169/938194f1-1071-4b34-bb3d-f41bc775313a

2024-03-20 15:46 UTC, bibibobobi commented on packages/mirror-tv-next/components/category/video/video-posts-list.tsx
> +    const {
試了很多辦法，好像都還是會卡住，可能還是要一次抓完，沒辦法在 swiper 換頁中間 load more

2024-04-08 08:34 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/video-posts-list.tsx
> +      if (width >= tabletWidthThreshold) {
感謝提醒，目前已於 [5e62259](https://github.com/mirror-tv/Tabris/pull/79/commits/5e62259fd0845b12d029bedf8f978ec96e812651) 改為使用 swiper api 實作

2024-04-08 08:35 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/video-posts-list.tsx
> +    const handleResize = () => {
感謝提醒，目前已於 [5e62259](https://github.com/mirror-tv/Tabris/pull/79/commits/5e62259fd0845b12d029bedf8f978ec96e812651) 改用 swiper api 實作

2024-04-08 08:35 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/video-posts-list.tsx
> +    const handleResize = () => {
他們的 gap 不一樣，已於 [5e62259](https://github.com/mirror-tv/Tabris/pull/79/commits/5e62259fd0845b12d029bedf8f978ec96e812651) 改用 swiper api 實作

2024-04-08 08:44 UTC, v61265 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +            categoryName="熱門新聞"
感謝提醒，已於 [35cc0e4](https://github.com/mirror-tv/Tabris/pull/79/commits/35cc0e4a9495227c0a52518acde2001237c21766) 修改。

2024-04-08 09:00 UTC, v61265 commented on packages/mirror-tv-next/styles/components/category/video/video-post-card.module.scss
> +  height: 100%;
哇這個完全沒想到，感謝提醒。不過其實下方文字最高可到三行，目前於 [5330851](https://github.com/mirror-tv/Tabris/pull/79/commits/5330851e6bf816a236be28c1e75bd6be385fb4d4) 先抓了 200px ，不確定會不會需要再精準一點？

2024-04-14 12:51 UTC, v61265 commented on packages/mirror-tv-next/styles/components/category/video/video-post-card.module.scss
> +  height: 100%;
又在 [149f6db](https://github.com/mirror-tv/Tabris/pull/79/commits/149f6dbf50dfb3e5124e6af22a436f308594b267) 限制了寬度，應該會比較好一點，要再麻煩你看看，感謝！

2024-04-14 12:55 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/video-posts-list.tsx
> +    const {
4/10 討論結果：
1. 卡住是不可避免的效果
2. 如果要完全避免卡住，則要將「next」按鈕和 「loadmore」按鈕分開，會需要 UI 支援
3. 不過舊版也有卡住彈回狀況（如果網路不夠好的話）
4. 先不處理，等新的 PM 要驗收到該頁時再麻煩他評估是否真的有需要處理

另雖然 PRD 上是寫 24 則，但舊版其實是直接滑到底，已於 [149f6db](https://github.com/mirror-tv/Tabris/pull/79/commits/149f6dbf50dfb3e5124e6af22a436f308594b267) 修改限制，再麻煩看看，感謝～

2024-04-14 12:56 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/video-posts-list.tsx
> +    const placeholderCount = 3 - (postsList.length % 3)
我在 [149f6db](https://github.com/mirror-tv/Tabris/pull/79/commits/149f6dbf50dfb3e5124e6af22a436f308594b267) 大部分交給 swiper 的 api 處理，並且新增 hook 偵測螢幕寬度（其他頁面也可以共用），希望我能通過該次學測 XD

2024-04-14 12:58 UTC, v61265 commented on packages/mirror-tv-next/components/category/video/video-posts-list.tsx
> +          {placeholder.map((item, index) => {
placeholder 是為了保持每一次換頁面都能以三個為一組，如果不滿三則就顯示空白。已於 [149f6db](https://github.com/mirror-tv/Tabris/pull/79/commits/149f6dbf50dfb3e5124e6af22a436f308594b267) 交由共通 hook 處理，再麻煩幫忙看一下這樣寫可不可行，感謝！

2024-04-16 06:12 UTC, erase2004 requested changes
關於 swiper 的部份，可以 apply patch，來使用 swiper 提供的方法簡化程式碼
[pr-79.patch](https://github.com/mirror-tv/Tabris/files/14987598/pr-79.patch)

2024-04-16 06:12 UTC, erase2004 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +  let categoryPosts: {
應該調整 type，增加 `categoryName` 屬性

2024-04-16 06:12 UTC, erase2004 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +              categoryName={getCategoryNameBySlug(list.categorySlug)}
這裡應該調整為直接使用 `categoryName` 屬性

2024-04-16 08:54 UTC, bibibobobi commented on packages/mirror-tv-next/styles/components/category/video/video-post-card.module.scss
> +  height: 100%;
我這邊看沒有問題了，辛苦了～

2024-04-17 05:53 UTC, v61265 commented
> 關於 swiper 的部份，可以 apply patch，來使用 swiper 提供的方法簡化程式碼
[pr-79.patch](https://github.com/mirror-tv/Tabris/files/14987598/pr-79.patch)

目前在 local 使用，好像沒辦法在第一屏和最後一屏隱藏前後，是正常的嗎？

2024-04-17 05:58 UTC, v61265 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +              categoryName={getCategoryNameBySlug(list.categorySlug)}
了解，已於 [7249d9d](https://github.com/mirror-tv/Tabris/pull/79/commits/7249d9d78abc018da2dac142040a0e1868337520) 修改

2024-04-17 05:58 UTC, v61265 commented on packages/mirror-tv-next/app/category/video/page.tsx
> +  let categoryPosts: {
了解，已於[7249d9d](https://github.com/mirror-tv/Tabris/pull/79/commits/7249d9d78abc018da2dac142040a0e1868337520) 修改

2024-04-17 06:19 UTC, erase2004 commented
> > 關於 swiper 的部份，可以 apply patch，來使用 swiper 提供的方法簡化程式碼
> > [pr-79.patch](https://github.com/mirror-tv/Tabris/files/14987598/pr-79.patch)
> 
> 目前在 local 使用，好像沒辦法在第一屏和最後一屏隱藏前後，是正常的嗎？詳細可看 [7249d9d](https://github.com/mirror-tv/Tabris/pull/79/commits/7249d9d78abc018da2dac142040a0e1868337520)

patch 的 Ln. 100 ~ Ln. 110 有針對樣式做調整，可以參考
另外，記得按 Re-request review 按鈕

2024-04-17 06:29 UTC, v61265 commented
> patch 的 Ln. 100 ~ Ln. 110 有針對樣式做調整，可以參考
另外，記得按 Re-request review 按鈕

抱歉是我漏看 >< 已於 [1a1fcff](https://github.com/mirror-tv/Tabris/pull/79/commits/1a1fcffbf454008dd6869125adbdc6668ef5459a) 調整！

2024-04-17 06:42 UTC, erase2004 approved these changes
還有 conflict 待解決 👏

2024-04-17 07:58 UTC, bibibobobi approved these changes

2024-04-17 08:07 UTC, merged